---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

### Books and book chapters    

Balland, P. A., Boschma, R., & Frenken, K. (2020) Proximity, Innovation and Networks: A Concise Review and Some Next Steps, Papers in Evolutionary Economic Geography, 20 (19): 1-75  

Crespo, P.A.., R. Boschma and P.A. Balland (2017) Resilience, networks and competitiveness: a conceptual framework, in: R. Huggins and P. Thompson (eds.) Handbook of Regions and Competitiveness. Cheltenham: Edward Elgar  

Balland, P.A. (2016) Relatedness and the Geography of Innovation, in: R. Shearmur, C. Carrincazeaux and D. Doloreux (eds) Handbook on the Geographies of Innovation. Northampton, MA: Edward Elgar  

Boschma, R., P.A. Balland and D. Kogler (2015) The geography of interfirm knowledge spillovers in bio-tech, in: F. Crespi and F. Quatraro (eds) The Economics of Knowledge, Innovation and Systemic Technology Policy. London/New York: Routledge   

Vicente, J., Balland, P.A. and Suire, R. (2013) The structure and geography of collaboration networks in the European GNSS industry: a 1-mode and 2-mode network analysis, in T. Scherngell (ed.) The geography of networks and R&D collaborations. New York, NY: Advances in Spatial Science Springer Series  

Boschma, R., Balland, P.A. and de Vaan, M. (2014) The Formation of Economic Networks: A Proximity Approach, in A. Torre and F. Wallet (eds.) Regional Development and Proximity Relations. Northampton, MA: Edward Elgar   

Balland, P.A., Boschma, R. and Frenken, K. (2013) Proximity and Innovation Networks: An Evolutionary Approach, in: P. Cooke (ed.) Re-framing Regional Development: Evolution, Innovation and Transition. New York, NY: Routledge   

Balland, P.A. (2010) Proximity and the Structure of Knowledge Networks: Evidence from the GNSS industry. Ph.D. Thesis, University of Toulouse. 