---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

### Journal articles   

Balland, P.A. & R. Boschma (2025) [An evolutionary approach to regional development traps in Europe](https://www.tandfonline.com/doi/full/10.1080/00343404.2025.2586708). *Regional Studies*, 59 (1: 1-16.   

Yamada, E., Balland, P.A., Kawakami, T. & Nemoto, J. (2025) [The structure and dynamics of the auto parts industry: Product space and complexity perspectives](https://www.sciencedirect.com/science/article/pii/S0954349X24001589). *Structural Change and Economic Dynamics*, 73: 472-485. 

Dong, Z.,Sun, S., Balland, P.A., & Zhang, W. (2025) [Environmental regulation promotes green technological diversification: evidence from Chinese cities](https://www.tandfonline.com/doi/full/10.1080/00343404.2025.2488207?scroll=top&needAccess=true), *Regional Studies*, 59 (1):1-18. 

Pinheiro, F., Balland, P.A., Boschma, R. & Hartmann, D. (2023) [The Dark Side of the Geography of Innovation. Relatedness, Complexity, and Regional Inequality in Europe](https://www.tandfonline.com/doi/full/10.1080/00343404.2022.2106362), *Regional Studies*, 59 (1): 1-16.   

Balland, P.A. & Boschma, R. (2024) [An Evolutionary Approach to Regional Development Traps in European Regions](http://econ.geo.uu.nl/peeg/peeg2420.pdf), *PEEG*, 24 (20): 1-52.    

Balland, P.A. & Boschma, R. (2024) [Brabant in goede positie om sleuteltechnologieën verder te ontwikkelen](https://esb.nu/wp-content/uploads/2024/09/D-080-085_IN_BallandBoschma.pdf), *ESB*, 109(4837S), 80-85.  

Liang, X., Hidalgo, C., Balland, P.A., Zheng, S. & Wang, J. (2024) [Intercity connectivity and urban innovation](https://www.sciencedirect.com/science/article/pii/S0198971524000218), *Computers, Environment and Urban Systems*, 109 (102092): 1-10.     

Steijn, M. Balland, P.A., Boschma, R. & Rigby, D. (2023) [Technological diversification of U.S. cities during the great historical crises](https://academic.oup.com/joeg/advance-article/doi/10.1093/jeg/lbad013/7209042), *Journal of Economic Geography*, 23 (6): 1303–1344.    

Balland, P.A. & Boschma, R. (2022) [Do scientific capabilities in specific domains matter for technological diversification in European regions?](https://www.sciencedirect.com/science/article/pii/S0048733322001172), *Research Policy*, 51 (10): 1-12.     

Boschma, R. & Balland, P.A. (2022) [Nieuwe methode brengt kansen op regionale vernieuwing in kaart](https://esb.nu/esb/20071100/nieuwe-methode-brengt-kansen-op-regionale-vernieuwing-in-kaart), *Economisch Statistische Berichten (ESB)*, 107 (4811S), 68:73.    

Uhlbach, W., Balland, P.A. & Scherngell, T. (2022) [Public R&D funding and new regional specialisations: The contingent role of technological relatedness](https://www.tandfonline.com/doi/full/10.1080/13662716.2022.2043147), *Industry and Innovation*, 29 (4): 511-532.        

Rigby, D., Roesler, C., Kogler, D., Boschma, R. & Balland, P.A. (2022) [Do EU regions benefit from Smart Specialization principles?](https://doi.org/10.1080/00343404.2022.2032628), *Regional Studies*,  56 (12): 2058-2073.     

Balland, P.A., Broekel, T., Diodato, D., Giuliani, E., Hausmann, R., O'Clery, N. & Rigby, D. (2022) [The new paradigm of economic complexity](https://www.sciencedirect.com/science/article/pii/S0048733321002420), *Research Policy*, 51 (3): 1-11.   

Dong, Z., Li, Y., Balland, P.A. & Zheng, S. (2022) [Industrial land policy and economic complexity of Chinese Cities](https://www.tandfonline.com/doi/full/10.1080/13662716.2021.1990022), *Industry and Innovation*, 29 (3).  

Balland, P.A., and Boschma, R. (2021) [Mapping the potentials of regions in Europe to contribute to new knowledge production in Industry 4.0 technologies](https://www.tandfonline.com/doi/full/10.1080/00343404.2021.1900557), *Regional Studies*, 55 (10-11): 1652-1666.    

Balland, P.A. and Boschma, R. (2021) [Complementary Inter-Regional Linkages and Smart Specialization: an Empirical Study on European Regions](https://www.tandfonline.com/doi/full/10.1080/00343404.2020.1861240), *Regional Studies*, 55 (6): 1059-1070.   

Maghssudipour, A., Balland, P.A., and Giuliani, E. (2021) [Cast apart by the elites: how status influences assortative matching in industrial clusters](https://www.tandfonline.com/doi/abs/10.1080/13662716.2020.1860738), *Industry & Innovation*, 28 (7): 836-859.   

Balland, P.A., Jara-Figueroa, C., Petralia, S., Steijn, M., Rigby, D., and Hidalgo, C. (2020) [Complex Economic Activities Concentrate in Large Cities](https://www.nature.com/articles/s41562-019-0803-3), *Nature Human Behavior*, 4: 248–254 [[PDF](https://paballand.github.io/writing/PDF/2020-NHB.pdf)]     

Ascani, A., Bettarelli, L., Resmini, L., and Balland, P. A. (2020) [Global networks, local specialisation and regional patterns of innovation](https://doi.org/10.1016/j.respol.2020.104031), *Research Policy*, 49 (8)    

Ascani, A., Balland, P.A., and Morrison, A. (2020) [Heterogeneous foreign direct investment and local innovation in Italian Provinces](https://doi.org/10.1016/j.strueco.2019.06.004), *Structural Change and Economic Dynamics*, 53: 388-401  

Balland, P.A., Boschma, R., Crespo, J. and Rigby, D. (2019) [Smart Specialization policy in the EU: Relatedness, Knowledge Complexity and Regional Diversification](https://doi.org/10.1080/00343404.2018.1437900), *Regional Studies*, 53 (9): 1252-1268 

Balland, P.A., Boschma, R., and Ravet, J. (2019) [Network dynamics in collaborative research in the EU, 2003–2017](https://doi.org/10.1080/09654313.2019.1641187), *European Planning Studies*, 27 (9): 1811-1837.  

Farinha, T., Balland, P.A., Morrison, A., and Boschma, R. (2019) [What drives the geography of jobs in the US? Unpacking relatedness](https://doi.org/10.1080/13662716.2019.1591940), *Industry and Innovation*, 26 (9): 988-1022  

Giuliani, E., Balland, P.A., and Matta, A. (2019) [Straining but not thriving: Understanding network dynamics in underperforming industrial clusters](https://doi.org/10.1093/jeg/lbx046), *Journal of Economic Geography*, 19 (1): 147–172 

Hidalgo, C., Balland, P.A., Boschma, R., Delgado, M., Feldman, M., Frenken, K., Glaeser, E., He, C., Kogler, D., Morrison, A.,  Neffke, F., Rigby, D., Stern, S., Zheng, S., and Zhu, S. (2018)  [The Principle of Relatedness](https://link.springer.com/chapter/10.1007/978-3-319-96661-8_46), *Unifying Themes in Complex Systems* (IX): 451-457  

Vicente, J., Balland, P.A., and Crespo, J. (2018) [Les fondements micro du changement structurel régional: Que nous enseignent 25 ans de proximités?](https://www.cairn.info/revue-d-economie-regionale-et-urbaine-2018-5-page-1013.html), *Revue d'Économie Régionale & Urbaine*, 5 (6): 1013-1041. 

Petralia, S., Balland, P.A., and Morrison, A. (2017) [Climbing the Ladder of Technological Development](https://doi.org/10.1016/j.respol.2017.03.012), *Research Policy*, 46 (5): 956–969 

Balland, P.A. and Rigby, D. (2017) [The Geography of Complex Knowledge](https://doi.org/10.1080/00130095.2016.1205947), *Economic Geography*, 93 (1): 1-23 

Balland, P.A. (2017) [A review of Why Information Grows? The Evolution of Order, from Atoms to Economies by César Hidalgo](https://onlinelibrary.wiley.com/doi/full/10.1111/tesg.12240), *Journal of Economic and Social Geography (TESG)*, 108 (2): 258–260  

Heimeriks, G., and Balland, P.A. (2016) [How Smart is Specialisation? An Analysis of Specialisation Patterns in Knowledge Production](https://academic.oup.com/spp/article-abstract/43/4/562/2514638?redirectedFrom=fulltext), *Science and Public Policy*, 43 (4): 562-574 

Balland, P.A., Belso-Martinez, J.A., and Morrison, A. (2016) [The Dynamics of Technical and Business Knowledge Networks in Industrial Clusters: Embeddedness, status or proximity?](https://www.tandfonline.com/doi/full/10.1080/00130095.2015.1094370), *Economic Geography*, 92 (1): 35-60 

Petralia, S., Balland, P.A., and Rigby, D. (2016) [Unveiling the geography of historical patents in the United States from 1836 to 1975](https://www.nature.com/articles/sdata201674), *Scientific Data*, 3 (160074): 1-14 

Balland, P.A., Rigby, D., and Boschma, R. (2015) [The Technological Resilience of U.S. Cities](https://academic.oup.com/cjres/article-abstract/8/2/167/333541), *Cambridge Journal of Regions, Economy and Society*, 8 (2): 167-184  

Balland, P.A., Boschma, R. and Frenken, K. (2015) [Proximity and Innovation: From Statics to Dynamics](https://www.tandfonline.com/doi/full/10.1080/00343404.2014.883598), *Regional Studies*, 49 (6): 907-920 

Boschma, R., Balland, P.A. and Kogler, D. (2015) [Relatedness and Technological Change in Cities: The rise and fall of technological knowledge in U.S. metropolitan areas from 1981 to 2010](https://academic.oup.com/icc/article-abstract/24/1/223/831624?redirectedFrom=fulltext), *Industrial and Corporate Change*, 24 (1): 223-250 

Broekel, T., Balland, P.A., Burger, M. and van Oort, F. (2014) [Modeling Knowledge Networks in Economic Geography: A Discussion of Four Empirical Strategies](https://link.springer.com/article/10.1007/s00168-014-0616-2), *The Annals of Regional Science*, 53 (2): 423-452  

Boschma, R., Heimeriks, G. and Balland, P.A. (2014) [Scientific Knowledge Dynamics and Relatedness in Bio-Tech Cities](https://www.sciencedirect.com/science/article/abs/pii/S004873331300125X), *Research Policy*, 43 (1): 107-114 

Balland, P.A., de Vaan, M. and Boschma, R. (2013) [The Dynamics of Interfirm Networks along the Industry Life Cycle: The Case of the Global Video Games Industry 1987-2007](https://www.jstor.org/stable/26158687?seq=1), *Journal of Economic Geography*, 13 (5): 741-765  

Balland, P.A., Suire, R. and Vicente, J. (2013) [Structural and Geographical Patterns of Knowledge Networks in Emerging Technological Standards: Evidence from the European GNSS Industry](https://www.tandfonline.com/doi/full/10.1080/10438599.2012.699773?scroll=top&needAccess=true), *Economics of Innovation and New Technology*, 22 (1): 47-72 

Balland, P.A. (2012) [Proximity and the Evolution of Collaboration Networks: Evidence from Research and Development Projects within the Global Navigation Satellite System (GNSS) Industry](https://www.tandfonline.com/doi/abs/10.1080/00343404.2010.529121), *Regional Studies*, 46 (6): 741-756 

Vicente, J., Balland, P.A. and Brossard, O. (2011) [Getting into Networks and Clusters: Evidence from the Midi-Pyrenean Global Navigation Satellite Systems (GNSS) Collaboration Network](https://www.tandfonline.com/doi/abs/10.1080/00343401003713340), *Regional Studies*, 45 (8): 1059-1078  

Vicente, J., Balland, P.A. and Brossard, O. (2011) [Getting into Networks and Clusters: Evidence from the Midi-Pyrenean Global Navigation Satellite Systems (GNSS) Collaboration Network](https://www.tandfonline.com/doi/abs/10.1080/00343401003713340), *Regional Studies*, 45 (8): 1059-1078 

Balland, P.A., Renda, A., Navarrete, C., Praas, R., Spanz, K., Ríos, F. (2024) [AI World: Watch the world transform with Artificial Intelligence](https://aiworld.eu/), *CEPS Digital Platforms*.    
