---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

### Policy reports      

Balland, P.A. (2022) [Innovation Policy for a Complex World](https://ec.europa.eu/info/sites/default/files/srip/2022/ec_rtd_srip-2022-report-chapter-14.pdf), *Chapter 14 of the Science, Research and Innovation Performance of the EU (SRIP) report*, European Commission's Directorate-General for Research and Innovation, Brussels.    

Dixson-Declève, S., Balland, P.A. et al. (2022) [Industry 5.0, a transformative vision for Europe : governing systemic transformations towards a sustainable industry](https://data.europa.eu/doi/10.2777/17322), *ESIR Policy Brief No 3*, European Commission's Directorate-General for Research and Innovation, Brussels.    

Dixson-Declève, S., Balland, P.A. et al. (2021) [The future of European universities](https://ec.europa.eu/info/publications/transformation-post-covid-future-european-universities_en), *ESIR Focus Paper*, European Commission's Directorate-General for Research and Innovation, Brussels.    

Dixson-Declève, S., Balland, P.A. et al. (2021) [Transformative nations, regions and cities as vectors for change](https://ec.europa.eu/info/publications/transformation-post-covid-transformative-nations-regions-and-cities-vectors-change_mt), *ESIR Focus Paper*, European Commission's Directorate-General for Research and Innovation, Brussels.    

Dixson-Declève, S., Balland, P.A. et al. (2021) [Global value chains : harnessing innovation to protect and transform the backbone of global trade](https://op.europa.eu/en/publication-detail/-/publication/c3bd86d6-c995-11eb-84ce-01aa75ed71a1/language-en/format-PDF/source-213423369), *ESIR Focus Paper*, European Commission's Directorate-General for Research and Innovation, Brussels.    

Dixson-Declève, S., Balland, P.A. et al. (2021) [Transformation post-COVID: Mobilising innovation for people, planet and prosperity](https://ec.europa.eu/info/publications/transformation-post-covid_en), *ESIR Policy Brief No 2*, European Commission's Directorate-General for Research and Innovation, Brussels.     

Dixson-Declève, S., Balland, P.A. et al. (2020) [Protect, prepare and transform Europe - Recovery and resilience post COVID-19](https://ec.europa.eu/info/publications/protect-prepare-and-transform-europe-recovery-and-resilience-post-covid-19_en), *ESIR Policy Brief No 1*, European Commission's Directorate-General for Research and Innovation, Brussels.    

Balland, P.A., and Boschma, R. (2020) [Smart Specialisation: beyond patents](https://ec.europa.eu/regional_policy/sources/docgener/brochure/smartspec_beyond_patents_en.pdf), European Commission's Directorate-General for Regional and Urban Policy, Brussels.   

Balland, P.A., and Boschma, R. (2019) [Exploring the impact of inter-regional linkages on regional diversification in Europe in the context of smart specialisation](https://ec.europa.eu/regional_policy/sources/docgener/brochure/impact_ir_linkages_en.pdf), European Commission's Directorate-General for Regional and Urban Policy, Brussels.

Balland, P.A., and Ravet, J. (2018) [Dynamic Network Analysis of the EU R&I Framework Programme](https://ec.europa.eu/info/sites/info/files/research_and_innovation/knowledge_publications_tools_and_data/documents/h2020_monitoring_flash_112018.pdf), Monitoring Flash for the European Commission's Directorate-General for Research and Innovation, Brussels.  

Boschma, R., Balland, P.A., Crespo, J., and Rigby, D. (2017) Linking impacts to open innovation: increasing local impact using the related variety and knowledge complexity concepts: empirical findings of regions patent data, Report for the RISE group, European Commission's Directorate-General for Research and Innovation, Brussels.   

