---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

### AI World  

Together with my team at CEPS and in partnership with Google I am developing the [AI World](https://aiworld.eu/)! Our mission is to democratize access to AI literacy by connecting the many dots and complex layers of Artificial Intelligence. The AI World demystifies AI by breaking down complex technologies into easily understandable pieces, exploring real-world impacts across industries, and showcasing AI hotspots globally. The platform connects foundational algorithms and everyday applications, highlight key companies and visionaries in the field, and prepare users for the AI-driven job market. With a focus on regulations and policy guidance, AI World offers a tailored learning experience for curious beginners, industry professionals, and policymakers alike. By providing interconnected profiles of AI hubs, sectors, jobs, key players, and concepts, this initiative seeks to equip users with the knowledge and insights needed to thrive in the rapidly evolving AI landscape.    

### EconGeo Package  

The R statistical software is increasingly used to perform analysis on the spatial distribution of economic activities. It contains state-of-the-art statistical and graphical routines not yet available in other software such as SAS, Stata, or SPSS. R is also free and opensource. Many graduate students and researchers, however, find programming in R either too challenging or end up spending a lot of their precious time solving trivial programming tasks. This is why I created the EconGeo package. Users do not need extensive programming skills to use it. EconGeo allows to easily compute a series of indices commonly used in the fields of economic geography, economic complexity, and evolutionary economics to describe the location, distribution, spatial organization, structure, and complexity of economic activities. Functions include basic spatial indicators such as the location quotient, the Krugman specialization index, the Herfindahl or the Shannon entropy indices but also more advanced functions to compute different forms of normalized relatedness between economic activities or network-based measures of economic complexity. By opening and sharing the codes used to compute popular indicators of the spatial distribution of economic activities, one of the goals of this package is to make peer-reviewed empirical studies more reproducible by a large community of researchers.  [Read more](http://econ.geo.uu.nl/peeg/peeg1709.pdf) 

