---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

### Economics of Networks - GEO3-3805      

Economists use concepts and methods from network science to understand a complex, global, and interconnected world. In network thinking, the fundamental unit of analysis consists of the relationships among interacting units rather than the individual characteristics of these units. The ability to analyze the particular way relationships are organized - i.e. the network structure - is crucial in understanding complex phenomena in nature and society. In this course, we discuss how a network perspective can help us to re-think key issues in economics. More specifically, this course will introduce concepts and methods to map and measure relationships and flows between people, firms, cities, economic sectors, communities, or any other element of a complex economic system. We will discuss how the structure of a system influences its overall performance, why the relative position in a network conditions the access to critical resources, and how relationships are created and dissolved over time. This course consists of lectures combined with computer exercises and online tutorials. [Course Manual](https://paballand.github.io/teaching/on.html)   

