---
---  

<link rel="stylesheet" href="styles.css" type="text/css">

<style>
body {
text-align: justify; font-size:12pt}
</style>

### Working papers    

Balland, P.A., Boschma, R. and Frenken, K. (2020) [Proximity, Innovation and Networks: A Concise Review and Some Next Steps](http://econ.geo.uu.nl/peeg/peeg2019.pdf), Papers in Evolutionary Economic Geography, 20 (19): 1-22   

iframe(width = "560", height = "315",
url_link = "https://www.youtube.com/embed/0fKg7e37bQE")

Dong, z. Sun, s.Balland, P.A., Zhang, W. (2022) [Environmental Regulation promotes Green Technological Diversification: Evidence from Chinese Cities](http://econ.geo.uu.nl/peeg/peeg2226.pdf), Papers in Evolutionary Economic Geography, 22 (26): 1-22    

Rigby, D., Roesler, C., Kogler, D., Boschma, R. and Balland, P.A. (2019) [Do EU regions benefit from smart specialization?](http://econ.geo.uu.nl/peeg/peeg1931.pdf) Papers in Evolutionary Economic Geography, 19 (31): 1-30      

Balland, P.A., and Boschma, R. (2019) [Mapping the potential of EU regions to contribute to Industry 4.0](http://econ.geo.uu.nl/peeg/peeg1925.pdf), Papers in Evolutionary Economic Geography, 19 (25): 1-21   

Dong, Z., Li, Y., Balland, P.A. and Zheng, S. (2019) [Industrial Land Policy and Economic Complexity of Chinese Cities](http://econ.geo.uu.nl/peeg/peeg1916.pdf), Papers in Evolutionary Economic Geography, 19 (16): 1-31   

Uhlbach, W.H, Balland, P.A. and Scherngell. T (2017) [R&D Policy and Technological Trajectories of Regions: Evidence from the EU Framework Programmes](http://econ.geo.uu.nl/peeg/peeg1722.pdf), Papers in Evolutionary Economic Geography, 17 (22): 1-22      
Balland, P.A. (2017) [Economic Geography in R: Introduction to the EconGeo Package](http://econ.geo.uu.nl/peeg/peeg1709.pdf), Papers in Evolutionary Economic Geography, 17 (09): 1-75   

Balland, P.A. (2017) EconGeo: Computing Key Indicators of the Spatial Distribution of Economic Activities, R package version 1.3: https://github.com/PABalland/EconGeo    

Petralia, S., Balland, P.A., and Rigby, D. (2016) HistPat Dataset, Harvard Dataverse, doi: 10.7910/DVN/BPC15W   