---
title: "CEPS-UNIDO PROJECT"
---

<style>
body {
text-align: justify}
</style>

# 0. PROPOSAL      

Mapping the use of AI in priority economic sectors is crucial to leverage new
opportunities for economic prosperity, societal benefit, and sustainable development.
By understanding where and how artificial intelligence technologies are being applied,
we can identify key areas for investment, spotlight gaps in the market or research, and
foster targeted development efforts. This strategic approach is not only crucial to
propel priority sectors forward but also for overall competitiveness and technological
sovereignty at the global stage.    

Providing such a mapping in a systemic and unbiased way is far from being an easy
task. Domain expert knowledge is, by definition, spread across sectors and
geographies, and the rapid pace of advancement in the field makes it hard to maintain
a current and thorough understanding of the latest developments. CEPS proposes a
data science approach to leverage hundreds of millions of patent documents (Google
Patents). The core of our approach is the use of machine learning tools to flag
innovative approaches that connect a specific AI technology (for instance AI
recommender systems) to a specific sectoral application (for instance chemistry)
through a specific use case (for instance recommender systems for chemical synthesis
planning).    

Our data analysis will then precisely quantify the use of specific AI technologies into
specific priority sectors. Our analysis could for instance reveal that 10% of AI
applications go to chemistry, 15% to renewable technologies…(these are hypothetical
numbers for illustration purpose). We will also give concrete examples of core AI use
cases in each sector. Results will be reported through high-end interactive data
visualizations.    

After having quantified the importance of AI in different sectors, we will use the same
root data to this time map the technological competitiveness of Ukraine in AI. For this
task we will use the inventor addresses listed on patent documents and assess the
relative comparative advantage of Ukraine in different fields of AI, how it changed over
time and complementarity potential with other European countries.
Results will be delivered as a policy brief of 10 pages maximum containing high-end
data visualizations, by the 31st of March 2024, for a budget of 40,000€ (exclusive of
VAT).   

# PART 1: MAPPING THE USE OF AI IN PRIORITY SECTORS   

## 1.0 PRIORITY SECTORS     
The UNIDO team communicated the following priority sectors: “Mechanical engineering, including mining, metallurgy, energy, railway, agricultural, chemical engineering, shipbuilding, aviation, aerospace, automotive, robotics; chemical and petrochemical industry; coal industry; defence industry; nuclear industry; research and teaching; agricultural sector; Medicine”'.

Given the strong heterogeneity within mechanical engineering we will provide our analysis for 18 priority sectors: Manufacturing, Mining, Metallurgy, Energy, Railway, Agricultural, Chemical engineering, Shipbuilding, Aviation, Aerospace, Automotive, Robotics, Chemical and petrochemical industry, Coal industry, Defense industry, Nuclear industry, Research and teaching, Medicine

Additionally, Olesya pointed out priority sectors defined by the Ukrainian government in 2022, identifying four areas of top priority: Military-tech (high-tech weapons), Metallurgy, mining industry, and mechanical engineering, Agriculture and food industry and IT industry. There is a strong overlap but a broad IT approach is missing from UNIDO so we might include.   

The first task is a classification task: flag AI and priority sectors in companies (crunchbase), patents (and publications).   

## 1.1 PENETRATION RATE ACROSS PRIO SECTORS   
https://www.paballand.com/ceps/unido/priority-sectors/vc/bar-chart-usd.html    
https://www.paballand.com/ceps/unido/priority-sectors/pat/bar-chart.html  

*Hightlights/key messages (examples, not yet analyzed, just to illustrate what we are going for)*  
- The medicine sector is the priority sector that has attracted the largest amount of $ invested in AI 
- The agricultural sector has the largest amount of AI firms   
- Out of the top 1000 start-ups in energy, 100 are in AI (10% penetration rate of AI in energy)   
- Stories on key use cases, gen AI is used in energy for XXX (Robert desk research + analysis of the crunchbase description put by PA)   
- GenAI is mostly used for XXX  

### AI use cases wheel (Robert)   

### AI - priority tech space  

### Histogram with all prio sectors of % of AI in top 1000    


### AI start-ups in priority sectors ($)   
*note: tiles are proportional to $ funding received until now*    
*some or all of these figures can be direclty included in the report*    
*how to group if not by geography? by other industries?*    
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/1-manufacturing-usd.html    
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/2-mining-usd.html     
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/3-metallurgy-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/4-energy-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/5-railway-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/6-agricultural-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/7-chemical-engineering-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/8-shipbuilding-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/9-aviation-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/10-aerospace-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/11-automotive-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/12-robotics-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/13-chemical-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/14-coal-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/15-defense-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/16-nuclear-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/17-education-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/18-medicine-usd.html  

### AI start-ups in priority sectors     
*note: 1 firm = 1 tile - just for the team to explore*    
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/1-manufacturing.html    
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/2-mining.html     
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/3-metallurgy.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/4-energy.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/5-railway.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/6-agricultural.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/7-chemical-engineering.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/8-shipbuilding.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/9-aviation.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/10-aerospace.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/11-automotive.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/12-robotics.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/13-chemical.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/14-coal.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/15-defense.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/16-nuclear.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/17-education.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/ai/18-medicine.html  


### Top 1000 start-ups in priority sectors ($)
*note: tiles are proportional to $ funding received until now - could be included in the appendix*    
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/1-manufacturing-usd.html    
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/2-mining-usd.html     
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/3-metallurgy-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/4-energy-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/5-railway-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/6-agricultural-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/7-chemical-engineering-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/8-shipbuilding-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/9-aviation-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/10-aerospace-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/11-automotive-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/12-robotics-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/13-chemical-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/14-coal-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/15-defense-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/16-nuclear-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/17-education-usd.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/18-medicine-usd.html  

### Top 1000 start-ups in priority sectors   
*note: 1 firm = 1 tile - just for the team to explore*    
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/1-manufacturing.html    
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/2-mining.html     
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/3-metallurgy.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/4-energy.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/5-railway.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/6-agricultural.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/7-chemical-engineering.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/8-shipbuilding.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/9-aviation.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/10-aerospace.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/11-automotive.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/12-robotics.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/13-chemical.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/14-coal.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/15-defense.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/16-nuclear.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/17-education.html  
https://www.paballand.com/ceps/unido/priority-sectors/vc/top-1000/18-medicine.html  


## 1.2 Technology analysis (patent data)   



# PART 2: Mapping the competitiveness of Ukraine in AI     

## 2.1 VC data (crunchbase)
Number of AI start-ups in the 27 largest European cities; Data source: Crunchbase, March 2024  


## 2.2 Technology analysis (patent data)   

