---
title: "Economic Complexity"
---

<style>
body {
text-align: justify}
</style>

#### Parcours LEA - Affaires Economiques Internationales - UT2 - Jean Jaurès  
#### [Pierre-Alexandre Balland](https://www.paballand.com)  

### Course description     
Economic complexity has emerged as a powerful paradigm to understand key issues in economics, geography, innovation studies, and other social sciences. Owing its popularity, in part, to its cross-disciplinary reach, the concept has shed new light on the variation in standards of living across nations (Hidalgo and Hausmann, 2009), differences in sophistication of technologies (Fleming and Sorenson, 2001), and the heterogeneous distribution of knowledge in space (Balland and Rigby, 2017). This excitement is not limited to academia. A host of policy institutions, ranging from international organizations such as the World Bank, World Economic Forum, European Commission, and OECD to national and local actors, have embedded both the methodology and conceptual framework of complexity into their core toolbox. Hence, as economic complexity moves from the periphery to the core of economic thinking and development policy, this class will equip students with the key concepts and tools of economic complexity. We will also talk about the link between a complex economic world and the spread of Covid-19 and the future of cities post-Covid 19. To warm-up on this last issue, see [this video](https://www.youtube.com/watch?v=C0YMLBT16n4).     

### Grading       
At the end of the class, each student will have to write a 1500-word essay (the topic of the essay will be distributed during lecture 3). Students need to upload the essay as a PDF to [this folder](https://www.dropbox.com/request/llPSmiSfsOESnupixdJb) by December 19.  

### Lecture 1: [Economic complexity and the wealth of nations](https://www.paballand.com/teaching/econx/lecture-1.pdf)    
**Time**: Monday, Nov. 2 [14:15-18:00]  
**Room**: Online    
**Note**: The class will take place online. You can join by following [this link](https://univ-tlse2.zoom.us/j/88185597312?pwd=M3NSdHJWV3d5aG1iTHREbU1UZDRYdz09)           
*Topics covered*  
- Why some countries are rich and other poor?  
- How to characterize the economic structure of countries?  
- What is economic complexity and how to measure it?  

*References*   
- Hidalgo, C. A., & Hausmann, R. (2009) [The building blocks of economic complexity](https://www.pnas.org/content/106/26/10570), Proceedings of the national academy of sciences, 106(26), 10570-10575.     
- Hausmann, R., Hwang, J., & Rodrik, D. (2007) [What you export matters](https://drodrik.scholar.harvard.edu/files/dani-rodrik/files/what-you-export-matters.pdf), Journal of economic growth, 12(1), 1-25.    
- The [Observatory of Economic Complexity](atlas.media.mit.edu)    

### [Lecture 2:  The geography of complex knowledge](https://www.paballand.com/teaching/econx/lecture-2.pdf)   
**Time**: Monday, Nov. 9 [14:15-18:00]   
**Room**: Online  
**Note**: The class will take place online. You can join by following [this link]( https://univ-tlse2.zoom.us/j/86761119948?pwd=cTJycDNFQ21Wekp1WFpNQlg2Yms2UT09)        

*Topics covered*  
- Why is knowledge so concentrated in space?  
- Why knowledge does not travel well?   
- Why are cities the engines of the knowledge-based economy?  

*References*  
- Balland, P.A., Jara-Figueroa, C., Petralia, S., Steijn, M., Rigby, D., and Hidalgo, C. (2020) [Complex Economic Activities Concentrate in Large Cities](https://www.nature.com/articles/s41562-019-0803-3), Nature Human Behavior, 4: 248–254     
- Balland, P.A. and Rigby, D. (2017) [The Geography of Complex Knowledge](https://media.wix.com/ugd/c5611b_4594fd3eb340409c9c57cceedd629928.pdf), Economic Geography, 93 (1): 1-23   
- [Uncovering tomorrow’s innovation hotspots](https://innovationmatters.economist.com/pdf/tomorrowsinnovationhotspots.pdf) (The Economist)  
- Cities and Covid-19: [NYT](https://www.nytimes.com/2020/07/21/business/cities-have-survived-pandemics-before-what-about-this-one.html) 
- Cities and Covid-19: [ERSA keynote](https://www.youtube.com/watch?v=C0YMLBT16n4)   

### Lecture 3:  [The principle of relatedness](https://www.paballand.com/teaching/econx/lecture-3.pdf)         
**Time**: Monday, Nov. 16 [14:15-18:00]   
**Room**: Online  
**Note**: The class will take place online. You can join by following [this link](https://univ-tlse2.zoom.us/j/81924955325?pwd=T0UySC9IcnpndEY2ZDBEYlBPZDhNQT09)        

*Topics covered*   
- How do countries and cities evolve over time?  
- How to move from making bananas to making computers?   
- What are the implications for policy?  

*References*  
Hidalgo, C., Balland, P.A., Boschma, R., Delgado, M., Feldman, M., Frenken, K., Glaeser, E., He, C., Kogler, D., Morrison, A., Neffke, F., Rigby, D., Stern, S., Zheng, S., and Zhu, S. (2018) [The Principle of Relatedness](https://link.springer.com/chapter/10.1007/978-3-319-96661-8_46), Unifying Themes in Complex Systems (IX): 451-457.   
- Hidalgo, C. A., Klinger, B., Barabási, A. L., & Hausmann, R. (2007) [The product space conditions the development of nations](https://arxiv.org/ftp/arxiv/papers/0708/0708.2090.pdf), Science, 317(5837), 482-487.    
- Balland, P.A., Boschma, R., Crespo, J. and Rigby, D. (2019) [Smart Specialization policy in the EU: Relatedness, Knowledge Complexity and Regional Diversification](https://doi.org/10.1080/00343404.2018.1437900), Regional Studies, 53 (9): 1252-1268.   



