---
title: "Urban Resilience - GEO4-3634"
author: "Pierre-Alexandre Balland"
---

### Course description  
In this course, we ask why some cities are able to survive major shocks, crises and sustained periods of decline while others ultimately collapse. In a global context of climate change, rapid urbanization, population growth, financial crises, and rising inequality this question is becoming increasingly prominent on the political agenda. Resilience theory has a long history in psychology, engineering, and ecology. It usually refers to the capacity of a system to 'bounce back', or in the context of complex social-ecological systems to the capacity of a system to continuously change and adapt its structure to changing economic, social and environmental conditions while maintaining its essential function. Understanding urban resilience, therefore, requires adopting a multi-level (social, economic, environmental, and political) view of the structure of urban systems. Understanding cities as complex adaptative systems deeply challenge our understanding of cities/regions and the role of urban and regional policy. In resilience thinking, what can be considered efficient (optimal) in the short run can also contradict with long-run sustainability, global sustainability, or the resilience of another city? Urban resilience is, therefore, a very complex question that requires rapid and flexible responses that often are context specific. As a result, the emerging research community working on urban resilience and urban sustainable development is dispersed, methodologically diverse, and lack coherence and academic consensus. Meanwhile, 'resilience initiatives' and concrete related actions are mushrooming in cities worldwide. Therefore a key objective of this course will be to develop student's critical reasoning. To reach this objective, this course will consist of weekly class discussions.         

### What you will learn   
1. Elements of complexity theory
2. What is resilience and what makes complex adaptative systems resilient? 
3. Evaluate the resilience of what to what?
4. How does urban resilience relate to global sustainability? 
5. How to integrate the economic, social, environmental, and political dimensions for sustainable urban development?  
6. How to apply resilience thinking for sustainable urban development?      

### Seminars  
We will meet weekly to actively discuss a specific dimension of urban resilience (economic, social, environmental...). The discussion will be opened by the lecturer to set the daily agenda, clarify key concepts, and highlight the main questions to be discussed. A group of students will then present their vision of this issue (based on journal articles, reports, case studies) and open the floor for discussion with other students. Students should use real-world examples of resilient cities as much as possible. Students are also strongly encouraged to draw upon their own background, reading, perceptions, and experiences.     

### Meet the instructors  
[Pierre-Alexandre Balland](https://www.paballand.com/) - p.balland@uu.nl  
[Ron Boschma](ron) - R.A.Boschma@uu.nl   

### Grading   
The overall grade for the class will be based on an individual research paper (80%) and a presentation in class (20%).      

### Research paper    
The research paper can be very academic (i.e. what is urban resilience and how to measure it), or very applied (i.e. how can Dutch cities limit the spread of COVID-19?). Each student will focus on a specific urban resilience issue and discuss the extent and the causes of this issues (academic) or how to solve this problem (applied) using an urban resilience and complexity science perspective. Remember that in the lectures and tutorials we discussed the topic of urban resilience from multiple perspectives (economic, social, environmental, governance) and we particularly insisted on the complex inter-connections between them. Make sure not to treat your urban resilience problem as a simple , non-linear issue. The preliminary idea will be presented by students during individual meetings (feed-back session on week 12). Please make sure to sign-up for the feedback sessions here and send a 1-page description of your idea to your instructor (Prof. Boschma or Prof. Balland) by March 15. You will then have 1 week to integrate the feed-back and prepare the presentation of your idea on week 13. The final version of the paper should be 1,500-word long maximum (excluding references) and contain graphics. The deadline to send the report is April 14. You need to upload your report to this folder (please do not send the report by email) as a PDF.  

### Readings  
There is no class reader. The weekly readings are provided on this web-page and slides/videos will be regularly uploaded here. All articles listed should be considered mandatory reading. Additional online materials might be assigned throughout the quarter.  

### Course Schedule   
For the online webinars we have created a 'Urban Resilience' team in MS Teams, you will be able to join the team by using this code: XXX.   

| Week |   Day    | Date  |     Time    |  Format   | Location |  Activity  | Lecturer   |
|:----:|:--------:|:-----:|:-----------:|:---------:|:--------:|:----------:|:----------:|
|   7  | Tuesday  | 16/02 | 14:00-15:30 |  Webinar  |  Online  | Lecture 1  |  Balland   |
|   7  | Tuesday  | 16/02 | 15:15-17:00 |  Webinar  |  Online  | Seminar 1  |  Balland   |
