---
title: "The Artificial Intelligence Revolution"
subtitle: "Prof. Pierre-Alexandre Balland"
author: "[Utrecht University](https://www.uu.nl/en) & [AI Toulouse Institute](https://en.univ-toulouse.fr/aniti)"
---

### Course description  
The AI revolution is taking the world by storm. We can only be mesmerized by intelligent machines driving cars, reading lung scans, or predicting what we will listen, watch, or buy better than humans. This extraordinary technology is still in its infancy but has already driven most of the S&P 500 growth while disrupting entire industries and rendering high-status skills completely obsolete. This class introduces the technical principles of modern AI algorithms & their business applications, discusses the macro-level impact of AI on the economy, and allows students to critically think about the skills they need for a world so different from the one our education system is designed for.   

### What you will learn  
- how AI will affect our future
- what are the skills & degrees humans need in an AI world 
- 

1. Economic geography data structure & management   
2. Compute basic EG indicators in R   
3. Compute relatedness and relatedness density  
4. Compute complexity  
5. Apply basic and advanced indicators to real world problems  

### Meet the instructor    
[Pierre-Alexandre Balland](https://www.paballand.com/) is a [French economist](https://scholar.google.com/citations?user=ORZg_McAAAAJ&hl=en&oi=ao) and one of Europe's leading experts on complex systems, the future of cities, artificial intelligence and blockchain technologies. He is a [Professor](https://www.uu.nl/staff/PMABalland/Profile) at [Utrecht University](https://www.uu.nl/en) and previously held positions at [MIT](https://www.media.mit.edu/people/balland/overview/) and  [UCLA](https://www.ucla.edu/). He is a Visiting Professor at the [Center for Collective Learning](https://centerforcollectivelearning.org/) of the [Artificial and Natural Intelligence Toulouse Institute](https://en.univ-toulouse.fr/aniti) and a research fellow at the [Center for Complex Systems Studies](https://www.uu.nl/en/research/centre-for-complex-systems-studies-ccss). Prof. Balland is also a high-level policy expert that  currently serves in the [ESIR](https://ec.europa.eu/info/research-and-innovation/strategy/support-policy-making/support-eu-research-and-innovation-policy-making/esir_en) group to advise the European Commission on innovation policy.  

### Computer Lab  
Students are expected to have followed to the 'Introduction to data science class'.    

### Grading    
Pass/fail based on a final pitch presentation.   

### Readings  
The full EconGeo manual can be found [here](http://econ.geo.uu.nl/peeg/peeg1709.pdf)  

### Course Schedule  

| Week |    Day   | Date  |     Time    |  Format   | Location |  Activity   | Lecturer   |
|:----:|:--------:|:-----:|:-----------:|:---------:|:--------:|:-----------:|:----------:|
|  6   | Monday   | 08/02 | 15:00-18:00 |  Lecture  |  Online  |   Lab 1     |  Balland   |
|  6   | Tuesday  | 09/02 |     -       |  Meeting  |  Online  | Ideation    |     -      |
|  6   | Wednesday| 10/02 | 16:00-18:00 |  Tutorial |  Online  |   Lab 2     |  Balland   |
|  6   | Thursday | 11/02 | 16:00-18:00 |   Q&A     |  Online  |    Q&A      |  Balland   |
|  6   |  Friday  | 12/02 | 16:00-18:00 |  Webinar  |  Online  |Presentations|  Balland   |

