---
title: "CEDIS3 MODULE 1: GENERAL SSS FRAMEWORK"
---

<style>
body {
text-align: justify}
</style>

#### Training proposal     
#### by [Pierre-Alexandre Balland](https://www.paballand.com) & Ron Boschma    

### Objectives         
In this module, Prof. Balland & Prof. Boschma will summarize key theoretical foundations, heuristics & principles of economic geography and economic complexity that are fundamental to the design and implementation of a successful smart specialization strategy. The main focus will be on regional diversification mechanisms, the principle of relatedness and economic complexity indicators. This module will also critically assess the S3 initiative in Europe, discuss its most recent evolution & related initiatives around the world. We will connect to potential data sources & metrics but always in an introductory fashion and staying at a high-level: making sure the intuiton is understood but never digging into more technical elements.       

### Structure   
The training consists of lectures (morning) combined with tutorials (afternoon) and is open to  participants with no prior knowledge of complexity thinking & metrics, economic geography or programming techniques. During the afternoon, participants are expected to apply the morning prinicples to concrete problems and present their approach.  

### Day 1: What is smart specialization really about?     

*Key concepts & objectives*    
- Why developing new specializations matter           
- Regional diversification, growth & resilience       
- The EU S3 policy: critical assessment, evolution & related initiatives around the world     

### Day 2: The principle of relatedness      

*Key concepts & objectives*     
- How do regions diversify over time      
- A unifying framework for regional development 
- Relatedness & Artificial Intelligence    

### Day 3: Economic complexity indicators     

*Key concepts & objectives*     
- What is economic complexity?        
- Economic complexity, growth & inequality       
- The challenges of measuring economic complexity (high-level)     

### Day 4: A framework for smart specialization        

*Key concepts & objectives*    
- Bringing together relatedness and economic complexity index  
- A powerful framework to prioritize investments   
- Overview of potential dataset    

### Day 5: Beyond relatedness & complexity          

*Key concepts & objectives*       
- Diversification & regional resilience      
- Thriving during the twin transition      
- The role of institutions        

 

### References   
Balland, P.A., Broekel, T., Diodato, D., Giuliani, E., Hausmann, R., O'Clery, N. & Rigby, D. (2022) [The new paradigm of economic complexity](https://www.sciencedirect.com/science/article/pii/S0048733321002420), *Research Policy*, 51 (3): 1-11.   

Balland, P.A., Boschma, R., Crespo, J. and Rigby, D. (2019) Smart Specialization policy in the EU: Relatedness, Knowledge Complexity and Regional Diversification, Regional Studies, 53 (9): 1252-1268.     

McCann, P., & Ortega-Argilés, R. (2015). Smart specialization, regional growth and applications to European Union cohesion policy. Regional studies, 49(8), 1291-1302.   

Foray, D., David, P. A., & Hall, B. (2009). Smart specialisation–the concept. Knowledge economists policy brief, 9(85), 100.    

