---
title: "CEDIS3 MODULE 7: PRODUCT SPACE ANALYSIS"
---

<style>
body {
text-align: justify}
</style>

#### Training proposal    
#### by [Pierre-Alexandre Balland](https://www.paballand.com) & Ron Boschma    

### Objectives        
The objective of this module is to provide participants with advanced network-based concepts and complexity tools to successfully implement a smart specialization strategy via the principle of relatedness & product space analysis. The product space is a generic term and the metrics taught in this module can be applied to the skill, occupation, scientific, technology space and other relevant networks for the implementation of a smart specialization strategy.      

### Structure  
The training consists of lectures combined with computer exercises and is open to participants with no prior knowledge of complexity thinking & metrics or programming techniques. Participants are expected to bring their laptop for the computer lab.        
 
### Day 1: Introduction to network thinking      

*Key concepts & objectives*    
- From attribute-based to network thinking  
- Networks in natural sciences, social sciences, business  
- Network thinking for policy and the S3    

*Lab 1*
- Basic matrix algebra  
- Network data management in R        
- Creating an igraph object (in R)  

### Day 2: Centrality & relatedness from 2-mode networks          

*Key concepts & objectives*    
- Introduction to graph theory  
- Global structural indicators      
- Degree, betweenend, closeness and eigenvector centrality      

*Lab 2*
- Structural analysis of global networks  
- Computing different forms of centrality    
- Mastering the igraph R package  

### Day 3: Relatedness metrics & relatedness density        

*Key concepts & objectives*    
- The nature of relatedness  
- The power of recommendation systems  
- From product relatedness to region-product relatedness density  

*Lab 3*
- Transposing matrices in R    
- Normalizing co-occurrences
- Computing relatedness density      

### Day 4: Graph visualization            

*Key concepts & objectives*    
- On the differences between graphs and networks  
- Elements of graph design  
- Maximum spanning trees  

*Lab 4*  
- Advanced network visualization in 2D    
- Interactive network visualization in 3D  v
- Graph layouts algorithms    

### Day 5: From the product space to complexity indicators              

*Key concepts & objectives*      
- Understanding the power and nature of eigenvectors  
- The Google Page Rank algorithm    
- On the relation between the product space and the economic complexity indicators  

*Lab 5*  
- Computing ECI and TCI in R  
- Modular complexity metrics  
- Pitfalls and solutions    

### References  
Balland, P.A. (2017) Economic Geography in R: Introduction to the EconGeo Package, Papers in Evolutionary Economic Geography, 17 (09): 1-75  

Balland, P.A. (2017) EconGeo: Computing Key Indicators of the Spatial Distribution of Economic Activities, R package version 1.3: https://github.com/PABalland/EconGeo  

Hidalgo, C. A., Klinger, B., Barabási, A. L., & Hausmann, R. (2007). The product space conditions the development of nations. Science, 317(5837), 482-487.  

Hidalgo, C. A., & Hausmann, R. (2009). The building blocks of economic complexity. Proceedings of the national academy of sciences, 106(26), 10570-10575.    

Hidalgo, C. A., Balland, P. A., Boschma, R., Delgado, M., Feldman, M., Frenken, K., ... & Zhu, S. (2018). The principle of relatedness. In Unifying Themes in Complex Systems IX: Proceedings of the Ninth International Conference on Complex Systems 9 (pp. 451-457). Springer International Publishing.  


