---
title: "Economic complexity for innovation policy"
---

<style>
body {
text-align: justify}
</style>

#### Training organized for DG RTD - European Commission     
#### by [Pierre-Alexandre Balland](https://www.paballand.com)  
#### Date: 27-28 April 2023 OR May 1-2 2023    

### Background     
Economic complexity offers a powerful paradigm to understand key societal issues and challenges of our time. The underlying idea is that growth, development, technological change, income inequality, spatial disparities, and resilience are the visible outcomes of hidden systemic interactions. The study of economic complexity seeks to understand the structure of these interactions and how they shape various socioeconomic processes. This emerging field relies heavily on big data and machine learning techniques.       

### Objectives         
In this training, Prof. Balland will tackle two main issues. The first is to summarize key theoretical foundations, heuristics & principles of economic complexity that are useful for research and innovation policy. The second is to introduce participants to the key tools and metrics developed in the economic complexity literature to solve policy strategy & evaluation problems. As a concrete example, this course will examine in detail how we can build recommendation systems for major public investment decisions in a complex world.     

### Structure   
The training consists of lectures combined with computer exercises and is open to  participants with no prior knowledge of complexity thinking & metrics or programming techniques. Participants are expected to bring their laptop for the computer lab.

### Day 1: Complexity thinking & structural network analysis  

*Key concepts*   
- Using complexity thinking to solve real-world problems  
- Key concepts for research and innovation policy  
- A framework to improve the EU innovation system  

*Computer lab (in R)*   
* Introduction to the R programming language   
* Network analysis of complex networks   
* Advanced network visualization    

### Day 2: Relatedness & ECI analysis    

*Key concepts*    
- Relatedness and economic complexity index  
- Mapping knowledge in countries/regions   
- A framework to prioritize EU investments   

*Computer lab (in R)*    
- Computing Relatedness (EconGeo Package)   
- Computing the ECI (EconGeo Package)   
- Plotting treemaps and the knowledge space   

### References   
Balland, P.A., Broekel, T., Diodato, D., Giuliani, E., Hausmann, R., O'Clery, N. & Rigby, D. (2022) [The new paradigm of economic complexity](https://www.sciencedirect.com/science/article/pii/S0048733321002420), *Research Policy*, 51 (3): 1-11.   
Balland, P.A. (2017) [Economic Geography in R: Introduction to the EconGeo Package](http://econ.geo.uu.nl/peeg/peeg1709.pdf), Papers in Evolutionary Economic Geography, 17 (09): 1-75.    

### Software installation for the computer lab       
You will find [here](https://www.paballand.com/install-r.html) a short tutorial that will guide you in the installation of:     
- R : a programming language and software environment for statistical computing and graphics   
- RStudio: a user-friendly interface for R   
- R packages: collection of R functions   

### Load data   
amz = "https://raw.githubusercontent.com/PABalland/ON/master/amz.csv"    
misel = "https://raw.githubusercontent.com/PABalland/ON/master/lesmis-el.csv"     
misnl = "https://raw.githubusercontent.com/PABalland/ON/master/lesmis-nl.csv"     
pat = "https://raw.githubusercontent.com/PABalland/ON/master/pat.csv"    


