---
title: "Advanced Methods and Techniques - GEO4-3902" 
subtitle: "Introduction to Artificial & Human Intelligence"
author: "Pierre-Alexandre Balland"
---

### Course description  
The AI revolution is rapidly taking the world by storm. We can only be mesmerized by how quickly intelligent machines have learned to drive cars, read lung scans, or predict what we will want to listen, watch, or buy better than any human. This extraordinary technology is still in its very infancy but has already driven most of recent stock market growth while disrupting entire industries and rendering high-status skills and occupations completely obsolete. In this class, Professor Balland provides an entry point for students to understand and thrive in this new AI world. It addresses the macro-level impact of AI on the economy, introduces the technical principles of modern AI algorithms, and invites students to critically think about the skills and values they need for a world so different from the ones our education system was designed for. AI does not make humans obsolete, it makes critical aspects of human intelligence even more important. The limits of AI are where humans thrive. This aspect will be addressed by Professor Van Liempt in particular. The class does not require specific mathematical or programming skills - just a deep interest in how AI will shape our future.      

### What you will learn  
1. The real-world problems AI is solving    
2. How AI creates a monopoly and a winner-takes-all society    
3. What AI cannot predict - and the increasing importance of human wisdom    
4. High-level understanding of machine learning, deep learning & network science   
5. The building blocks of AI systems: network data structures   
6. How to transform data into meaningful, actionable insights   
7. How to build an AI recommendation system to solve a real-world problem   
8. Basic programming skills in R and Nvivo      
9. Grounded theory   
10. Qualitative methods    

### Meet the instructors  
[Pierre-Alexandre Balland](https://www.paballand.com/) - p.balland@uu.nl  
[Ilse van Liempt](https://www.uu.nl/staff/ICvanLiempt/Profile) - I.C.vanLiempt@uu.nl  
[Anne de Bruin](n.a.debruin@uu.nl) - n.a.debruin@students.uu.nl      
[Sergio Petralia](https://sergiopetralia.wixsite.com/research) - s.g.petralia@uu.nl      

### Computer Lab
No prior knowledge in quantitative methods or statistical computing is required to follow this course. We will use the R statistical software (open source) and Nvivo. Labs will take place online and students will need a personal computer to follow this class.    

### Grading    
The overall grade for the class will be based on a final pitch presentation as a 10-min video (60%) and 2 assignments (40%).   

### Assignments  
Essay assignment (#1) should be submitted to [this Dropbox folder](https://www.dropbox.com/request/4qIQHVxU2huVCElkMTqF). Quantitative-oriented assignments need to be submitted to [this Dropbox folder](https://www.dropbox.com/request/mUvyRnpnbaInI2hXgWKs) and qualitative-oriented assignments should be submitted to [this folder](https://www.dropbox.com/request/SVGO0USAnxcegIgie8Pd). If assignments combine both approaches, please submit to the quantitative folder. 

### Exam  
The final exam will reward your creative mind. Groups of 3 students will have pitch their idea on how to solve a real world problem using a recommender system solution. Full details will be given during lecture 5 and students will have 2 weeks to prepare their pitch (deadline on November 5).  

### Readings  
There is no class reader. The weekly readings are provided on this web-page and slides/videos will be regularly uploaded here. All articles listed should be considered mandatory reading. Additional online materials might be assigned throughout the quarter.  

### Course Schedule  

| Week |   Day  | Date  |     Time    |   Location    |  Activity  | Lecturer   |
|:----:|:------:|:-----:|:-----------:|:-------------:|:----------:|:----------:|
|  38  | Wed    | 22/09 | 09:00-10:45 |  Ruppert D    | Lecture 1  |  Balland   |
|  38  | Wed    | 22/09 | 11:00-12:30 |  MIN - 207    | Tutorial 1 |  Balland   |
|  38  | Wed    | 22/09 |      -      |    Online     |    Lab 1   |  Balland   |
|  38  | Wed    | 22/09 | 13:15-15:00 |EDUC - THEATRON| Lecture 2  |  Balland   |
|  38  | Wed    | 22/09 | 15:30-17:00 |    Online     |    Lab 2   |  Petralia  |
|  39  | Friday | 01/10 | 11:00-12:15 |  Ruppert D    | Lecture 3  | van Liempt |
|  40  | Friday | 08/10 | 14:00-15:15 |  MIN - 2.02   | Lecture 4  | van Liempt |
|  41  | Friday | 15/10 | 09:00-10:45 |  BBG - 119    | Tutorial 2 | van Liempt |
|  41  | Friday | 15/10 | 11:00-12:45 |  BBG - 119    | Tutorial 2 | van Liempt |
|  41  | Friday | 15/10 | 13:15-15:00 |  BOL - 1.070  | Tutorial 2 | van Liempt |
|  41  | Friday | 15/10 | 15:15-17:00 |  BOL - 1.070  | Tutorial 2 | van Liempt |
|  42  | Friday | 22/10 | 13:15-15:00 |  MIN - 2.02   | Lecture 5  |  Petralia  |
|  42  | Friday | 22/10 | 15:15-17:00 |    Online     |    Lab 3   |  Petralia  |

##### **Lecture 1: Artificial intelligence and human society**  [SLIDES](https://paballand.github.io/teaching/ids/lecture-1.pdf)   
*Topics covered*  
- Overview of class   
- Scope and limits of the AI revolution   
- Key applications of AI for business and society    
- Predicting in a complex world    
- Winners and losers of the AI revolution    

*References*   
- [The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies](https://www.amazon.com/Second-Machine-Age-Prosperity-Technologies/dp/0393350649) by Erik Brynjolfsson & Andrew McAfee    
- [Prediction Machines: The Simple Economics of Artificial Intelligence](https://www.amazon.com/Prediction-Machines-Economics-Artificial-Intelligence/dp/1633695670) by Ajay Agrawal, Joshua Gans & Avi Goldfarb        
- [AI Superpowers: China, Silicon Valley, And The New World Order](https://www.amazon.com/AI-Superpowers-China-Silicon-Valley/dp/132854639X) by Kai-Fu Lee    

*Homework*   
Assignment 1: 1000-word essay on *AI and the winner-takes-all-economy* (deadline: 01/10)  

##### **Lab 1: Introduction to R**  [SLIDES](https://paballand.github.io/teaching/ids/L1&Lab1.pdf)   
*Topics covered*  
- Software for network analysis   
- Introduction to R and RStudio   
- Basic programming skills   

*References*  
- http://www.statmethods.net  
- https://pballand.wixsite.com/balland/install-r   

##### **Lecture 2: Artificial intelligence tools and principles**  [SLIDES](https://paballand.github.io/teaching/ids/lecture-2.pdf)     
*Topics covered*  
- What AI is and what AI is not   
- AI, network science, ML and DL   
- The data matrix behind key AI applications   
- Talking to your computer: demystifying programming language   
- Working principles of recommendation systems    

*References*  
- [The Observatory of Economic Complexity (OEC) website](http://atlas.media.mit.edu/)  
- LeCun, Yann, Yoshua Bengio, and Geoffrey Hinton (2015) [Deep learning](https://www.nature.com/articles/nature14539), *Nature* (you don't have to understand it all, just skim through it)  
- Pierre-Alexandre Balland, Cristian Jara-Figueroa, Sergio G. Petralia, Mathieu P. A. Steijn, David L. Rigby & César A. Hidalgo (2020) [Complex economic activities concentrate in large cities](https://www.nature.com/articles/s41562-019-0803-3#:~:text=Complex%20economic%20activities%2C%20such%20as,as%20apparel%20or%20paper%20manufacturing.), *Nature Human Behavior*     
- Amazon's description of their [collaborative filtering AI system](https://www.amazon.science/the-history-of-amazons-recommendation-algorithm)    
- [Why data is the most valuable resource](https://www.economist.com/leaders/2017/05/06/the-worlds-most-valuable-resource-is-no-longer-oil-but-data) according to *The Economist*      

##### **Lab 2: Importing & visualizing data in R**  [SCRIPT](https://paballand.github.io/teaching/ids/Lab2.R) & [VIDEO]("https://www.dropbox.com/s/zyy9ktrz8u9ebqj/Lab2.MP4?dl=0")                      
- Read and transform attribute data   
- Read and transform linked data (network data)  
- Network graphs, treemaps, pie charts, histograms, scatter plots and more in R   

##### **Lecture 3: Introduction to qualitative research**  
*Topics covered*  
- Case-study research  
- Nature of qualitative research   

*References*  
- Flyvbjerg, B. (2006). Five misunderstandings about case-study research. Qualitative inquiry, 12(2), 219-245.  
- Hennink, M., Hutter, I. and A. Bailey (2011) , Qualitative Research Methods, chapter 2 The nature of qualitative research.  pp. 8-28. Sage  

##### **Lecture 4: Analyzing qualitative data**   
*Topics covered*  
- Peculiarty of qualitative data  
- Ethnographies  

*References*  
- Corbin, J. & A. Strauss (2008) Basics of qualitative research, chapter 4 Strategies for qualitative data analysis, pp. 65-85. London: SAGE.  
- Crang, M. & I. Cook (2007) Doing ethnographies, chapter 8 Analysing field materials, pp. 131-149. London: SAGE  

##### **Tutorial 2: Qualitative data analysis using nvivo**   
*Homework*  
Assignment 2 (deadline: 13/10)  

##### **Lecture 5: Predictions and Models**  [SLIDES](https://paballand.github.io/teaching/ids/L5.pdf)      
*Topics covered*  
- Simplicity always win  
- Simple and complex models  
- Beware of correlations  
- On causality  
- AI recommendation system (network model)   
- Learn how to read a regression table   

##### **Lab 3: Predictions and Models in R**  [SCRIPT](https://paballand.github.io/teaching/ids/Lab3.R) & [VIDEO]("https://web.microsoftstream.com/video/3b152335-ba70-47bf-ac36-f43828f264e4")              
- OLS  
- Logit models    
- AI recommendation system (network model)    


