---
title: "Methods and Techniques Specialisation - GEO4-3921" 
subtitle: "Module 6: EconGeo (using R)"
author: "Pierre-Alexandre Balland"
---

### Course description  
This online module is a simple introduction on how to do economic geography in R using the EconGeo package (Balland, 2017). Users do not need extensive programming skills to use it. EconGeo allows to easily compute a series of indices commonly used in the fields of economic geography, economic complexity, and evolutionary economics to describe the location, distribution, spatial organization, structure, and complexity of economic activities.  

### What you will learn  
1. Economic geography data structure & management   
2. Compute basic EG indicators in R   
3. Compute relatedness and relatedness density  
4. Compute complexity  
5. Apply basic and advanced indicators to real world problems  

### Meet the instructor    
[Pierre-Alexandre Balland](https://www.paballand.com/) - p.balland@uu.nl   

### Computer Lab  
Students are expected to have followed to the 'Introduction to data science class'.    

### Grading    
Pass/fail based on a final pitch presentation.   

### Readings  
The full EconGeo manual can be found [here](http://econ.geo.uu.nl/peeg/peeg1709.pdf)  

### Course Schedule  

| Week |    Day   | Date  |     Time    |  Format   | Location |  Activity   | Lecturer   |
|:----:|:--------:|:-----:|:-----------:|:---------:|:--------:|:-----------:|:----------:|
|  6   | Monday   | 08/02 | 15:00-18:00 |  Lecture  |  Online  |   Lab 1     |  Balland   |
|  6   | Tuesday  | 09/02 |     -       |  Meeting  |  Online  | Ideation    |     -      |
|  6   | Wednesday| 10/02 | 16:00-18:00 |  Tutorial |  Online  |   Lab 2     |  Balland   |
|  6   | Thursday | 11/02 | 16:00-18:00 |   Q&A     |  Online  |    Q&A      |  Balland   |
|  6   |  Friday  | 12/02 | 16:00-18:00 |  Webinar  |  Online  |Presentations|  Balland   |

