---
title: "The New Science of Cities - GEO4-3632"
author: "Pierre-Alexandre Balland"
---

### Course description  
The new science of cities uses recent advances in network thinking, complexity science and big data management to understand how cities function, grow, and change. Beyond buildings and urban landscapes, the soul of a city is defined by a complex web of social interactions that are fueled by urban diversity and urban density. These interactions foster new inventions, social change, and wealth creation. In this course, we discuss how a complexity perspective can help us to analyze these interactions and re-think key issues in economic and urban geography. More specifically, it will introduce concepts and methods to map and measure relationships and flows between people, firms, cities, or any other element of a complex spatial system. The class is composed of lectures, interactive seminars, and group meetings.     

### What you will learn   
1. What a complexity-based paradigm is, and how it can be applied to cities
2. How to identify, describe, and analyze the economic and social structure of cities
3. How the structure of cities influence their growth and quality of life
4. General underlying patterns common to all cities
5. How the new science of cities can be used to plan smart cities   

### Seminars  
Students will actively prepare weekly tutorials in order to perform a truly interactive seminar. The idea is to use the concept and tools introduced by the lecturer to re-think (or solve) a real-world urban problem. I encourage you to think big and break the rules. Creativity is rewarded in this class.  

### Meet the instructors  
[Pierre-Alexandre Balland](https://www.paballand.com/) - p.balland@uu.nl  
[Ron Boschma](ron) - R.A.Boschma@uu.nl  
[Bas Spierings](bas) - b.spierings@uu.nl  
[Anne de Bruin](n.a.debruin@uu.nl) - n.a.debruin@uu.nl     

### Grading   
The overall grade for the class is based on an group research paper (60% of the grade) and a individual Twitter thread (40% of the grade).    

### Research paper    
The research paper can be very academic, or very applied. Each group will focus on a specific urban issue and discuss the extent and the causes of this issues (academic) or how to solve this problem (applied) using a new science of cities perspective (network thinking and complexity science). The preliminary idea will be presented and discussed in individual meetings. The paper should be 1,500-word long maximum (excluding references) and contain graphics. The deadline to send the report is November 5. You need to upload your report to this [folder](https://www.dropbox.com/request/D8jyFYaQjgVp7FoV0hTI) (please do not send the report by email) as a PDF.   

### Twitter thread       
A Twitter thread is a series of connected Tweets in which you will publicly explain a concept, an idea, the contribution of a scholar/activist or your position on a specific issue. The overall topic should be connected to issues discussed in class. [Here](https://twitter.com/pa_balland/status/1353736308955492354?s=20) is an example of a thread on *the role of interregional linkages for Smart Specialisation Strategy*. You can use your own public Twitter profile (ideally) but you can also set-up a fake account if you prefer. Your thread represents an individual effort (not in group) and should be published by November 12. As soon as the thread is published please share the link in this [document](https://docs.google.com/document/d/1EcHy2Iqfy81AX_CxXhjlGgc-M97PvQX4AM4rmfQ6kCM/edit?usp=sharing).    

### Readings  
There is no class reader. The weekly readings are provided on this web-page and slides/videos will be regularly uploaded here. All articles listed should be considered mandatory reading. Additional online materials might be assigned throughout the quarter.  

### Course Schedule   
  

| Week |   Day    | Date  |     Time    |      Location    |  Activity  | Lecturer   |
|:----:|:--------:|:-----:|:-----------:|:----------------:|:----------:|:----------:|
|  36  | Thursday | 08/09 | 09:00-10:45 |DALTON - 6.27     | Lecture 1  |  Balland   |
|  36  | Thursday | 08/09 | 11:00-12:45 |DALTON - 6.27     | Tutorial 1 |  Balland   |
|  37  | Thursday | 15/09 | 09:00-10:45 |BESTUURS - LIEREGG| Lecture 2  |  Balland   |
|  37  | Thursday | 15/09 | 11:00-12:45 |BESTUURS - 033D   | Tutorial 2 |  Balland   |
|  38  | Thursday | 22/09 | 09:00-10:45 |RUPPERT - 114     | Lecture 3  |  Balland   |
|  38  | Thursday | 22/09 | 11:00-12:45 |RUPPERT - 136     | Tutorial 3 |  Balland   |
|  39  | Tuesday  | 27/09 | 13:15-15:00 |      -           | Lecture 4  |  Balland   |
|  39  | Tuesday  | 27/09 | 15:15-17:00 |      -           | Tutorial 4 |  Balland   |
|  40  | Thursday | 06/10 | 09:00-10:45 |BESTUURS - 033D   | Lecture 5  |  Spierings |
|  40  | Thursday | 06/10 | 11:00-12:45 |BESTUURS - 033D   | Tutorial 5 |  Spierings |
|  41  | Thursday | 13/10 | 09:00-10:45 |DALTON - 6.27     | Lecture 6  |  Boschma    |
|  41  | Thursday | 13/10 | 11:00-12:45 |DALTON - 6.27     | Tutorial 6 |  Boschma   |
|  42  |    -     |   -   |      -      |  Online          |      -     |  Balland   |
|  42  |    -     |   -   |      -      |  Online          |      -     |  Spierings |
|  43  |    -     |   -   |      -      |  Online          |      -     |  Balland   |
|  43  |    -     |   -   |      -      |  Online          |      -     |  Spierings |  

##### **Lecture 1: Complex systems and network thinking** [SLIDES](https://github.com/PABalland/PABalland.github.io/raw/master/teaching/nsc/L1.pdf)  
*Topics covered*  
- Overview of class   
- Introduction to network thinking   
- Complex networks in natural sciences, social sciences, and business   
- Key structural patterns of real-world complex systems   
- Cities as complex systems?   

*References*
- Balland, P.A. (2017) A review of Why Information Grows? The Evolution of Order, from Atoms to Economies by Cesar Hidalgo, Journal of Economic and Social Geography (TESG), 108 (2): 258-260 [PDF](http://econ.geo.uu.nl/balland/Balland-2017-Tijdschrift_voor_economische_en_sociale_geografie.pdf)    
- Barabasi, A. L. (2012) The network takeover, Nature Physics 8 (1), 14-16 [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_c65333e3828c4a7a854f20ff09e4b127.pdf)    
- Barabasi, A. L. (2016) Network Science. Cambridge, England: Cambridge University Press - Chapter 2 [PDF](http://networksciencebook.com/chapter/2)   
- Weaver, W (1948) Science and Complexity, American Scientist, 36: 536 (1948) [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_ebdf2b396bf8462e963ec657fa5560a4.pdf)    

##### **Lecture 2: Urban Scaling Laws** [SLIDES](https://github.com/PABalland/PABalland.github.io/raw/master/teaching/nsc/L2.pdf)    
*Topics covered*   
- Kleiber's law and scaling  
- Sublinear and superlinear scaling in cities  
- Cities and social interactions  
- Complexity and urban scaling  

*References*   
- Bettencourt, L. M. (2013). The origins of scaling in cities. science, 340(6139), 1438-1441 [PDF]  
- Balland, P.A., Jara-Figueroa, C., Petralia, S., Steijn, M., Rigby, D., and Hidalgo, C. (2020) Complex Economic Activities Concentrate in Large, Nature Human Behavior [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_1283ebc1906c424c86af86921e7f17d3.pdf)    
- Batty, M. (2009) Cities as complex systems: Scaling, interaction, networks, dynamics and urban morphologies. In Encyclopedia of complexity and systems science (pp. 1041-1071). New York: Springer [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_0b3ab4b746e7437697b00882761c27e2.pdf)   

##### **Lecture 3: Complexity & Urban Growth** [SLIDES](https://github.com/PABalland/PABalland.github.io/raw/master/teaching/nsc/L3.pdf)   
*Topics covered*   
- What is economic complexity and how to measure it  
- Why complexity leads to sustainable growth  
- Knowledge complexity and place-dependent dynamics  

*References*  
- Balland, P.A. and Rigby, D. (2017) The Geography of Complex Knowledge, Economic Geography, 93 (1): 1-23 [PDF](https://media.wix.com/ugd/c5611b_4594fd3eb340409c9c57cceedd629928.pdf)   
- Hidalgo, C. A., & Hausmann, R. (2009). The building blocks of economic complexity. Proceedings of the national academy of sciences, 106(26), 10570-10575 [PDF](http://www.pnas.org/content/pnas/106/26/10570.full.pdf)   
- [The Observatory of Economic Complexity (OEC) website](http://atlas.media.mit.edu/)   

##### **Lecture 4: The Principle of Relatedness** [SLIDES](https://github.com/PABalland/PABalland.github.io/raw/master/teaching/nsc/L4.pdf)      
*Topics covered*   
- Predicting changes in spatial systems  
- Why complexity leads to sustainable growth  
- Knowledge complexity and place-dependent dynamics  

*References*  
- Hidalgo, C., Balland, P.A., Boschma, R., Delgado, M., Feldman, M., Frenken, K., Glaeser, E., He, C., Kogler, D., Morrison, A.,  Neffke, F., Rigby, D., Stern, S., Zheng, S., and Zhu, S. (2018)  The Principle of Relatedness,  Proceedings of the 20th International Conference on Complex Systems, forthcoming [PDF](http://econ.geo.uu.nl/peeg/peeg1830.pdf)   
- Hidalgo, C. A., Klinger, B., Barabasi, A. L., & Hausmann, R. (2007). The product space conditions the development of nations. Science, 317(5837), 482-487 [PDF](http://barabasi.com/f/220.pdf)    


##### **Lecture 5: Spatial trialectics, relational public space and critical urbanism**  
*Topics covered*   
- Production of space  
- Materiality of imaginaries  
- Othering, exclusion and resistance  

*References*   
- Colomb, C. (2012), Pushing the urban frontier: temporary uses of space, city marketing,
and the creative city discourse in 2000s Berlin. Journal of Urban Affairs: 34(2), 131-152 [PDF](https://doi.org/10.1111/j.1467-9906.2012.00607.x)   
- Leary, M.E. (2009), The production of space through a shrine and vendetta in Manchester: Lefebvre's spatial triad and the regeneration of a place renamed Castlefield. Planning Theory & Practice, 10(2), 189-212 [PDF](https://doi.org/10.1080/14649350902884573)    
- Schaller, S. and S. Guinand (2018), Pop-up landscapes: a new trigger to push up land value? Urban Geography, 39(1), 54-74 [PDF](https://doi.org/10.1080/02723638.2016.1276719)   
- Young, C., M. Diep and S. Drabble (2006). Living with difference? The 'cosmopolitan city' and urban reimagining in Manchester, UK. Urban Studies: 43(10), 1687-1714 [PDF](https://doi.org/10.1080%2F00420980600888486)    


##### **Lecture 6: Smart Specialization and beyond**   
*Topics covered*   
- Smart Specialization Framework  
- Using data to govern cities  
- Extra-regional linkages  

*References*   
- Balland, P.A., Boschma, R., Crespo, J. and Rigby, D. (2019)  Smart Specialization policy in the EU: Relatedness, Knowledge Complexity and Regional Diversification, Regional Studies, forthcoming [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_94433b170c40428d9fea06a58dcef6d1.pdf)   
- An [evaluation](https://paballand.github.io/3-smart-spec-key-tech-data-FR10.html) of Ile de France opportunities in some key technologies   
- INET Webinar [How Regions Can Re-invent Themselves](https://www.youtube.com/watch?v=BmMTvj6IWRk) by Pierre-Alexandre Balland  
- Balland and Boschma [EU report](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_bd5558e001b9472ab0b53c6207b05ab6.pdf)     



