---
title: "Economics of Networks - GEO3-3805"
author: "Pierre-Alexandre Balland"
---

### Course description  
Economists use concepts and methods from network science to understand a complex, global, and interconnected world. In network thinking, the fundamental unit of analysis consists of the relationships among interacting units rather than the individual characteristics of these units. The ability to analyze the particular way relationships are organized - i.e. the network structure - is crucial in understanding complex phenomena in nature and society. In this course, we discuss how a network perspective can help us to re-think key issues in economics. More specifically, this course will introduce concepts and methods to map and measure relationships and flows between people, firms, cities, economic sectors, communities, or any other element of a complex economic system. We will discuss how the structure of a system influences its overall performance, why the relative position in a network conditions the access to critical resources, and how relationships are created and dissolved over time. This course consists of lectures combined with computer exercises and online tutorials.  

### What you will learn  
1. What a network-based paradigm is, and how it can be applied to economics
2. How to identify, describe, and analyze the structure of networks 
3. How the structure of economic systems influence their performance
4. How networks evolve in space and over time
5. Basic programming skills (in R) and advanced network analysis techniques  

### Meet the instructors  
[Pierre-Alexandre Balland](https://www.paballand.com/) - p.balland@uu.nl  
[Anne de Bruin](n.a.debruin@uu.nl) - n.a.debruin@uu.nl     

### Grading  
The overall grade for the class will be based on an individual mid-term exam (50%) and a report of a collective research project (50%).

### Research project  
The report of the research project involves the collection, examination, and analysis of economic network data followed by a short essay reviewing empirical and theoretical arguments. Groups of 2-3 students will focus on a specific economic question and use network thinking and network analysis tools to answer it. Make sure not to apply blindly the tools you will learn in the class but rather tell a story with your network data. You will be guided along your projects in group meetings. The outcome of your project should be (1) a slidedeck (10 slides max), (2) a 2000-word long paper (excluding references) and (3) the R scripts you used to produce the network graphs and compute the network metrics. This material should be submitted to [this](https://www.dropbox.com/request/LwSV7hxd0i4qTatae9hZ) Dropbox folder by November 1 at the latest (week 44 is free so you can finalize the project).  

### Group meetings  
One of the most important parts of this class is your network project. You will learn many new skills, that can lead to more advanced research or even a business opportunity. But this project is also challenging, from truly applying network thinking and collecting the data, to presenting your finding in a clear and structured way. These group meetings are milestones to make sure that you stay on schedule and do not get lost in the project complexity.  

### Readings  
There is no class reader. The weekly readings are provided on this web-page and slides/videos will be regularly uploaded here. All articles listed should be considered mandatory reading. Additional online materials might be assigned throughout the quarter.  

### Course Schedule   
For the online webinars we have created an 'Economics of Networks' team in MS Teams, you will be able to join the team by using this code: 8a4fps9.  

| Week |   Day    | Date  |     Time    |  Format   | Location |  Activity  | Lecturer   |
|:----:|:--------:|:-----:|:-----------:|:---------:|:--------:|:----------:|:----------:|
|  37  | Thursday | 10/09 | 13:30-15:00 |  Webinar  |  Online  | Lecture 1  |  Balland   |
|  37  | Thursday | 10/09 | 15:15-17:00 |  Webinar  |  Online  |    Lab 1   |  Balland   |
|  38  | Thursday | 17/09 | 14:00-15:30 |  Webinar  |  Online  | Lecture 2  |  Balland   |
|  38  |     -    |   -   |      -      |   Video   |  Online  |    Lab 2   |  Balland   |
|  38  | Thursday | 17/09 | 15:45-17:00 |  Webinar  |  Online  | Lecture 3  |  Balland   |
|  38  |     -    |   -   |      -      |   Video   |  Online  |    Lab 3   |  Balland   |
|  39  | Thursday | 24/09 | 13:15-17:00 |    Call   |  Online  |   Meeting  |  De Bruin  |
|  40  | Thursday | 29/09 | 11:00-12:45 |  Webinar  |  Online  | Lecture 4  |  Balland   |
|  40  |     -    |   -   |      -      |   Video   |  Online  |    Lab 4   |  Balland   |
|  40  | Thursday | 01/10 | 13:15-17:00 |    Call   |  Online  |   Meeting  |  De Bruin  |
|  41  | Thursday | 08/10 | 13:15-15:00 |    Exam   |  Online  |     Exam   |  De Bruin  |
|  42  | Thursday | 15/10 | 13:15-17:00 |    Call   |  Online  |   Meeting  |  De Bruin  |
|  43  | Thursday | 22/10 | 13:15-17:00 |    Call   |  Online  |   Meeting  |  De Bruin  |


##### **Lecture 1: Introduction to network science**  [SLIDES](https://github.com/PABalland/PABalland.github.io/raw/master/teaching/on/L1&Lab1.pdf)     
*Topics covered*    
- Overview of class   
- Introduction to network thinking   
- Networks in natural sciences, social sciences, and business   
- Economics and networks   

*References*   
- Barabasi, A. L. (2012) The network takeover, Nature Physics 8 (1), 14-16 [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_c65333e3828c4a7a854f20ff09e4b127.pdf)   
- Ter Wal, A. L., and Boschma, R. A. (2009) Applying social network analysis in economic geography: framing some key analytic issues. The Annals of Regional Science 43 (3): 739-756 [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_0931e6065e214ba1933018110703fae3.pdf)   
- Hanneman, R.A. and Riddle, M. (2005) Introduction to social network methods. Riverside, CA:  University of California, Riverside - Chapter 1 [PDF](http://faculty.ucr.edu/~hanneman/nettext/C1_Social_Network_Data.html)   
- An application of ONA by Deloitte [PDF](https://www2.deloitte.com/us/en/pages/human-capital/articles/organizational-network-analysis.html)   

##### **Lab 1: Network Analysis in R - Introduction to R**  [SLIDES](https://github.com/PABalland/PABalland.github.io/raw/master/teaching/on/Lab1.html)   
*Topics covered*   
- Network data collection (research projects)   
- Software for network analysis   
- Introduction to R and RStudio   
- Basic programming skills   

References   
- http://www.statmethods.net   
- https://pballand.wixsite.com/balland/install-r 

##### **Lecture 2: Graph theory and Complex networks**   
*Topics covered*   
- Graphs and matrices   
- Key concepts: nodes, links, structure   
- Random networks   
- Small worlds   
- Growing networks    
- Key structural patterns of real-world networks   
- Principles to keep in mind when working with your own network data   
- Scope and milestones of the project   

*References*  
- Barabasi, A. L. (2016) Network Science. Cambridge, England: Cambridge University Press - Chapter 2 [PDF](http://networksciencebook.com/chapter/2)  
- Hanneman, R.A. and Riddle, M. (2005) Introduction to social network methods.  Riverside, CA:  University of California, Riverside - Chapters 2 [PDF](http://faculty.ucr.edu/~hanneman/nettext/C2_Formal_Methods.html), 3 [PDF](http://faculty.ucr.edu/~hanneman/nettext/C3_Graphs.html), 5 [PDF](http://faculty.ucr.edu/~hanneman/nettext/C5_%20Matrices.html) & 7 [PDF](http://faculty.ucr.edu/~hanneman/nettext/C7_Connection.html)   
- Barabasi, A. L., and Albert, R. (1999) Emergence of scaling in random networks, Science 286 (5439): 509-512 [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_0f8a62d4615e4821859c249a3a0802af.pdf)   
- Watts, D. J., and Strogatz, S. H. (1998) Collective dynamics of 'small-world' networks, Nature 393 (6684): 440-442 [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_a47348d589f943d38faf71c2c1769b79.pdf)   

##### **Lab. 2: Network analysis in R - Network Data**   
*Topics covered*  
- Basic matrix algebra [VIDEO 2.1](https://www.youtube.com/watch?v=cac1yqxxwWM&feature=youtu.be)  
- Network data management [VIDEO 2.2](https://www.youtube.com/watch?v=TAojsuvZRsI&feature=youtu.be)   
- Creating an igraph object (from raw data) [VIDEO 2.3](https://www.youtube.com/watch?v=gRkCgIejXCI)   

*References*   
- Balland, P.A. (2017) Economic Geography in R: Introduction to the EconGeo Package, Papers in Evolutionary Economic Geography, 17 (09): 1-75 [PDF](https://peeg.wordpress.com/2017/05/09/17-09-economic-geography-in-r-introduction-to-the-econgeo-package/)   
- Csardi G, Nepusz T: The igraph software package for complex network research, InterJournal, Complex Systems 1695. 2006 [PDF](http://www.necsi.edu/events/iccs6/papers/c1602a3c126ba822d0bc4293371c.pdf)   

##### **Lecture 3: Centrality and power**     
*Topics covered*    
- Why positions of actors/nodes in a network matter   
- Degree, betweenness, and closeness centrality   
- Strength of weak ties, structural holes, and network closure     

*References*   
- Granovetter, M. (1985) Economic action and social structure: The problem of embeddedness, American journal of sociology 91 (3): 481-510 [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_0c0ac97925d74aaa914141a15b3bd734.pdf)   
- Burt, R. S. (2004) Structural holes and good ideas. American journal of sociology 110 (2): 349-399 [PDF](http://www.econ.upf.edu/docs/seminars/burt.pdf)   
- Hanneman, R.A. and Riddle, M. (2005) Introduction to social network methods.  Riverside, CA:  University of California, Riverside - Chapters 9 [PDF](http://faculty.ucr.edu/~hanneman/nettext/C9_Ego_networks.html) & 10 [PDF](http://faculty.ucr.edu/~hanneman/nettext/C10_Centrality.html)  

##### **Lab. 3: Network analysis in R - Computing global & local indicators**   
*Topics covered*  
- Structural analysis of global networks [VIDEO 3.1](https://www.youtube.com/watch?v=JI3ibVmeopU&feature=youtu.be)  
- Computing different forms of centrality [VIDEO 3.2](https://youtu.be/57kuxJ-dVAI)  
- Mastering the igraph R package  

##### **Lecture 4: The economy as a complex system**   
*Topics covered*   
- Endogenous mechanisms of growth in economic systems  
- Mapping economic systems as 2-mode networks  
- Relatedness and evolution   
- Predicting changes in economic systems  
- An application to European innovation policy  

*References*   
- Hidalgo, C., Balland, P.A., Boschma, R., Delgado, M., Feldman, M., Frenken, K., Glaeser, E., He, C., Kogler, D., Morrison, A.,  Neffke, F., Rigby, D., Stern, S., Zheng, S., and Zhu, S. (2018)  The Principle of Relatedness,  Proceedings of the 20th International Conference on Complex Systems, forthcoming [PDF]  
- Hidalgo, C. A., Klinger, B., Barabasi, A. L., & Hausmann, R. (2007). The product space conditions the development of nations. Science, 317(5837), 482-487 [PDF](http://barabasi.com/f/220.pdf)  
- Balland, P.A., Boschma, R., Crespo, J. and Rigby, D. (2019)  Smart Specialization policy in the EU: Relatedness, Knowledge Complexity and Regional Diversification, Regional Studies, forthcoming [PDF](https://2c2e773f-85c0-4039-818c-ea517fc75085.filesusr.com/ugd/c5611b_94433b170c40428d9fea06a58dcef6d1.pdf)   
- INET Webinar [How Regions Can Re-invent Themselves](https://www.youtube.com/watch?v=BmMTvj6IWRk) by Pierre-Alexandre Balland  

##### **Lab. 4: Mapping the structure of economic systems in R**    
*Topics covered*   
- Computing relatedness between (economic) activities [VIDEO 4.1](https://youtu.be/l5T0lGTQfWw)  
- Relatedness density and predicting entry (diversification) [VIDEO 4.2](https://youtu.be/1G5bbk8ZXDA)  
- Visualization of complex networks [VIDEO 4.3](https://youtu.be/rRK0o9GRCsg)  

**Additional reading**    
Students are not required to purchase any books to follow this course. If you are interested in additional reading, these three books make an excellent introduction to the world of network science and network analysis:  

- Barabasi, A.L. (2002) Linked: The New Science of Networks. Cambridge, MA: Perseus.  
- Newman, M.E.J. (2010) Networks: An Introduction. Oxford, England: Oxford University Press.  
- Wasserman, S., and Faust, K. (1994) Social Network Analysis: Methods and Applications. Cambridge, England: Cambridge University Press.  

**Useful websites**   

- Full introductory online textbook on social network analysis by Robert Hanneman and Mark Riddle: http://faculty.ucr.edu/~hanneman/nettext/  
- Full introductory online textbook on network science by Albert-L?szl? Barab?si: http://barabasilab.neu.edu/networksciencebook/downlPDF.html   
- A simple introduction to R by Robert Kabacoff: http://www.statmethods.net/   
- The website of Tom Snijders on dynamic network analysis: https://www.stats.ox.ac.uk/~snijders/siena/  

