---
title: "Urban Resilience - GEO4-3634"
author: "Pierre-Alexandre Balland"
output: html_document
---

<style>
body {
text-align: justify}
</style>

### Course description  
In this course, we ask why some cities are able to survive major shocks, crises and sustained periods of decline while others ultimately collapse. In a global context of climate change, rapid urbanization, population growth, financial crises, and rising inequality this question is becoming increasingly prominent on the political agenda. Resilience theory has a long history in psychology, engineering, and ecology. It usually refers to the capacity of a system to 'bounce back', or in the context of complex social-ecological systems to the capacity of a system to continuously change and adapt its structure to changing economic, social and environmental conditions while maintaining its essential function. Understanding urban resilience, therefore, requires adopting a multi-level (social, economic, environmental, and political) view of the structure of urban systems. Understanding cities as complex adaptative systems deeply challenge our understanding of cities/regions and the role of urban and regional policy. In resilience thinking, what can be considered efficient (optimal) in the short run can also contradict with long-run sustainability, global sustainability, or the resilience of another city? Urban resilience is, therefore, a very complex question that requires rapid and flexible responses that often are context specific. As a result, the emerging research community working on urban resilience and urban sustainable development is dispersed, methodologically diverse, and lack coherence and academic consensus. Meanwhile, 'resilience initiatives' and concrete related actions are mushrooming in cities worldwide. Therefore a key objective of this course will be to develop student's critical reasoning. To reach this objective, this course will consist of weekly class discussions.   

### What you will learn   
1. Elements of complexity theory
2. What is resilience and what makes complex adaptative systems resilient? 
3. Evaluate the resilience of what to what?
4. How does urban resilience relate to global sustainability? 
5. How to integrate the economic, social, environmental, and political dimensions for sustainable urban development?  
6. How to apply resilience thinking for sustainable urban development?    

### Meet the instructors  
[Pierre-Alexandre Balland](https://www.paballand.com/) - p.balland@uu.nl  
[Ron Boschma](https://scholar.google.com/citations?user=qi-zxOAAAAAJ&hl=en) - R.A.Boschma@uu.nl   
 
### Structure of the class  
Each week, the lecturer will introduce a key theme on urban resilience. After this lecture, a seminar will be prepared and organized by a group of 2 students. They present their vision based on the articles of that week and lead a discussion with other students on the key theme of that week. To stimulate discussion, the group of students should prepare 5 propositions (preferably critical or even provocative) based on the articles and bring those in discussion. All students are required to read all articles of that week beforehand. Students are strongly encouraged to draw upon their own background, reading, perceptions, and experiences. The allocation of students to groups is done by the coordinator and can be found on Blackboard.     

### Grading   
The overall grade for the class will be based on an individual research paper (60%) and a group presentation in class (40%).    

### Research paper     
The research paper can be very academic (i.e. what is urban resilience and how to measure it), or very applied (i.e. how can Dutch cities limit the spread of COVID-19?). Each student will focus on a specific urban resilience issue and discuss the extent and the causes of this issues (academic) or how to solve this problem (applied) using an urban resilience and complexity science perspective. Remember that in the lectures and tutorials we discussed the topic of urban resilience from multiple perspectives (economic, social, environmental, governance) and we particularly insisted on the complex inter-connections between them. Make sure not to treat your urban resilience problem as a simple , non-linear issue. The final version of the paper should be 1,500-word long maximum (excluding references) and contain graphics. The deadline to send the report is April 14. You need to upload your report to this folder (please do not send the report by email) as a PDF.      

### Group presentation  
On week 13, groups of 2 students will present their vision for resilient cities in the 21st century. Students can focus on the trend of their choices (remote working, pandemics, technological change, climate impact) and its potential future impact on cities in the coming years.    

### Readings  
There is no class reader. The weekly readings are provided on this web-page and slides/videos will be regularly uploaded here. All articles listed should be considered mandatory reading. Additional online materials might be assigned throughout the quarter.  

### Course Schedule   
For the online webinars we have created a 'Urban Resilience' team in MS Teams, you will be able to join the team by using this code: na81q34  

| Week |   Day    | Date  |     Time    |     Location    |  Activity      | Lecturer   |
|:----:|:--------:|:-----:|:-----------:|:---------------:|:--------------:|:----------:|
|   7  | Thursday | 16/02 | 09:00-10:45 |DALTON 500 - 5.27| Intro to class |  Boschma   |
|   7  | Thursday | 16/02 | 11:00-12:45 |DALTON 500 - 5.27| Lecture 1      |  Boschma   |
|   8  | Thursday | 23/02 | 09:00-10:45 |DALTON 500 - 3.27| Lecture 2      |  Boschma   |
|   8  | Thursday | 23/02 | 11:00-12:45 |DALTON 500 - 3.27| Seminar 2      |  Boschma   |
|   9  | Thursday | 02/03 | 09:00-10:45 |DALTON 500 - 3.27| Lecture 3      |  Boschma   |
|   9  | Thursday | 02/03 | 11:00-12:45 |DALTON 500 - 3.27| Seminar 3      |  Boschma   |
|  10  | Thursday | 09/03 | 09:00-10:45 |    BBG - 007    | Lecture 4      |  Balland   |
|  10  | Thursday | 09/03 | 11:00-12:45 |    BBG - 007    | Seminar 4      |  Balland   |
|  11  | Thursday | 16/03 | 09:00-10:15 |MIN 207| Lecture 5      |  Balland   |
|  11  | Thursday | 16/03 | 10:30-11:45 |MIN 207| Seminar 5      |  Balland   |
|  11  | Thursday | 16/03 | 12:00-13:00 |MIN 416| CCSS event      |  Jeroen van den Bergh   |
|  12  | Tuesday  | 21/03 | 13:30-15:00 |DALTON 500 - 1.19| Lecture 6      |  Balland   |
|  12  | Tuesday  | 21/03 | 15:15-17:00 |DALTON 500 - 1.19| Seminar 6      |  Balland   |
|  12  | Thursday | 23/03 | 09:00-12:45 |BBG – 065        | Presentations  |  Balland   |

### Lecture 1:  Evolutionary Economic Geography            
       
*Topics covered*  
- Overview of class   
- Introduction to urban resilience & sustainability: framing key challenges   
- Key thinkers in EEG     
- Why an evolutionary approach is needed to think about urban resilience    


*References*   
- Boschma, R.A. and Frenken K. (2006) Why is economic geography not an evolutionary science? Towards an evolutionary economic geography, Journal of Economic Geography 6 (3): 273–302.    
- Martin R. and Sunley P. (2006) Path dependence and regional economic evolution. Journal  of Economic Geography 6 (4): 395–437.    
- Boschma, R. and K. Frenken (2018) Evolutionary Economic Geography, in G. Clarke, M. Feldman, M. Gertler & D. Wojcik (eds.), New Oxford Handbook of Economic Geography, Oxford University Press, 213-229.    
- Simmie, J. and Martin R. (2010) The economic resilience of regions: towards an evolutionary approach, Cambridge Journal of Regions, Economy and Society 3, 27–43. https://doi.org/10.1093/cjres/rsp029    
 

### Lecture 2: Economic resilience     

*Topics covered*  
- Different forms of Regional Resilience  
- Labour dynamics and resilience   
- Long-term resilience of cities   

*References*  
- Martin, R. (2012) Regional economic resilience, hysteresis and recessionary shocks, Journal of Economic Geography 12, 1-32   
- Boschma, R. (2015) Towards an evolutionary perspective on regional resilience. Regional Studies 49, (5), 733-751   
- Diodato, D. and Weterings, A. B. (2015). The resilience of regional labour markets to economic shocks. Exploring the role of interactions among firms and workers, Journal of Economic Geography 15 (4), 723-742
- Neffke, F., M. Henning and R. Boschma (2011), How do regions diversify over time? Industry relatedness and the development of new growth paths in regions, Economic Geography 87 (3), 237-265      
- Steijn, M., R. Boschma, P. Balland and D. Rigby (2019) Technological Diversification of U.S. Cities during the Great Historical Crises, Papers in Evolutionary Economic Geography, no. 19.01, Utrecht University, Utrecht    

### Lecture 3: Environmental resilience   

*Topics covered*   
- Sustainability transitions    
- Cleantech diversification mechanisms  
- The role of policy, political conditions & institutions   

*References*  
- Hansen, T., & Coenen, L. (2015). The geography of sustainability transitions: Review, synthesis and reflections on an emergent research field. Environmental Innovation and Societal Transitions, 17, 92–109. doi:10.1016/j.eist.2014.11.001    
- Garud, R., & Karnøe, P. (2003). Bricolage versus breakthrough: Distributed and embedded agency in technology entrepreneurship. Research Policy, 32, 277–300. doi:10.1016/S0048-7333(02)00100-2    
- Berge, van den M., A. Weterings and F. Alkemade (2020) Do existing regional specialisations stimulate or hinder diversification into cleantech? Environmental Innovation and Societal Transitions 35, 185–201.    
- Santoalha, A. and R. Boschma (2021) Diversifying in green technologies in European regions: does political support matter?, Regional Studies 55 (2), 182-195.    
- Kapetaki, Z., Ruiz, P. et al. (2020) Clean energy technologies in coal regions: Opportunities for jobs and growth: Deployment potential and impacts, EUR 29895 EN, Publications Office of the European Union, Luxembourg.   

### Lecture 4: AI & the city          

*Topics covered*  
- What is AI?   
- How AI will affect jobs?   
- Which cities will gain/lose in the new AI world?   

*References*  
- Frey, C. B., & Osborne, M. A. (2017). The future of employment: how susceptible are jobs to computerisation?. Technological forecasting and social change, 114, 254-280   
- Balland, P.A. and Boschma R. (2019) Mapping the potential of EU regions to contribute to Industry 4.0, Papers in Evolutionary Economic Geography 19 (25), 1-21   
- How will automation affect different U.S. Cities by Morgan Frank et al.   
- Uncovering tomorrow's innovation hotspots (The Economist) 

### Lecture 5: Covid-19, fat tails & the city

*Topics covered*   
- Additive and multiplicative growth rates  
- The nature of decision making in a complex world  
- Complexity, vulnerability and probability of extinction    

*References*  
- Dixson-Decleve, S., Balland, P.A. et al. (2020) [Protect, prepare and transform Europe - Recovery and resilience post COVID-19](https://ec.europa.eu/info/sites/info/files/research_and_innovation/groups/esir/ec_rtd_esir-recovery-resilience-covid19.pdf), European Commission's Directorate-General for Research and Innovation, Brussels  
- Cirillo, P. & Taleb, N. (2020) Tail risk of contagious diseases, Nature Physics 16: 606-613  

### Lecture 6: From policy initiatives to resilience       

*Topics covered*   
- Economic policy  
- Social policy    
- Environmental policy  
- Complex interdependencies between different elements of resilience   

*References*  
- MacKinnon, D., & Derickson, K. D. (2013). From resilience to resourcefulness: A critique of resilience policy and activism. Progress in human geography, 37(2), 253-270.    
- Iammarino, S., Rodriguez-Pose, A., & Storper, M. (2019). Regional inequality in Europe: evidence, theory and policy implications. Journal of economic geography, 19(2), 273-298.    
- Balland, P. A., Boschma, R., Crespo, J., & Rigby, D. L. (2019). Smart specialization policy in the European Union: relatedness, knowledge complexity and regional diversification. Regional studies, 53(9), 1252-1268    




