---
title: 'Forge Ahead or Fall Behind: The Imperative of a United Europe of Artificial
  Intelligence '
output:
  html_document:
    df_print: paged
---

<style>
body {
text-align: justify}
</style>

<br />

# [ESIR Group, European Commission](https://research-and-innovation.ec.europa.eu/strategy/support-policy-making/shaping-eu-research-and-innovation-policy/esir_en) 

<br />

### [Pierre-Alexandre Balland](https://www.paballand.com) & [Andrea Renda](https://www.eui.eu/people?id=andrea-renda)     

<br />



<font size="4">

Europe has been at the forefront of every industrial revolution and consistently delivered the most complex products and technologies to the world. No need to go back to the steam engine, the dynamo, or wireless communications. Just a few decades ago CERN was busy developing no less than the World Wide Web while EU countries and companies were coming together in an unprecedented way to create the Global System for Mobile Communications (GSM). Collaborations between different European ecosystems have also brought us Airbus, Ariane, Pressurized Nuclear Reactors and Complex Medical Imaging Devices. Today with the rise of Artificial Intelligence we are witnessing a revolution that will drastically transform the way we live, the way we work and pretty much re-distribute power at a global scale. To say the least, Europe is not leading this revolution. The world is not using European AI products or infrastructure and we lack a united, ambitious AI initiative at the EU scale. This needs to change. Europe cannot afford to sit on the sidelines of what might be the most disruptive technological revolution of human history. Artificial Intelligence is also a domain where ethics and technology need to go hand-in-hand as it is pretty much impacting the entire fabric of our society. But the clock is ticking and we need to massively invest to support a truly pan-European ecosystem that encourages AI innovation while safeguarding fundamental rights.    

AI is not such a young field, fluctuating through periods of fervent enthusiasm and relative dormancy since its inception in the 1950s. But the combination of massive internet data, computing power and deep learning capabilities has launched the first true wave of the AI revolution where we finally went beyond proof-of-concepts and reached mass usage. Despite having significant talent and capabilities, Europe missed this first phase because of the lack of a unified digital market. In this first phase, access to a large pool of internet users powered the massive comparative advantage and the US and China. Via positive reinforcement feedback loops, platforms such as Amazon, Facebook, Tencent, Google, Alibaba or Netflix attracted users by offering free or quasi-free services and in ‘exchange’ gathered massive amounts of data. This data was then used to train and deploy AI recommender systems to increase scrolling, search and engagement eventually forging the ‘big techs’ we all know. Europe had immense talent, technology and ideas too. iWiW (International Who is Who) was a Hungarian social networking web service that started almost 2 years before Facebook. It grew to 4 million - almost all internet users in Hungary – before dying when Facebook finally entered the market. E-commerce platforms or streaming services have also been strongly divided and siloed in Europe, so American and Chinese companies grew to be modern data-gathering Goliaths and took over the European digital market. Figure 1 shows the market cap of top companies worldwide in industries where AI, and in particular recommender systems, play a role. The dominance of the big US and Chinese tech companies is staggering. 


<iframe src="https://www.paballand.com/asg/esir/ai/companies.html" height="505" width="910" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" data-external="1"></iframe>      

<br />

Missing this first wave has an obvious economic impact – but it also removes the ability to shape the development of AI towards societal goals. Recommender systems are very powerful engines in a complex world. There is so much content on the internet these days that we need systems to search, select and match users to content. AI recommender systems function by analyzing a user's past behavior, preferences, and interactions to suggest content, products, or services. So in simple terms, what Amazon, Twitter, or Netflix recommender systems do is that they personalize content and decide what users see. This is usually based on a technology called collaborative filtering. So this is what these systems do, they filter. But how? And with which purpose? In practice this is simple, to maximize scrolling time and user engagement. This is by nature not neutral and the design and implementation of these systems can create inequality, but also echo chambers and polarization. This happens by exposing users to information and opinions similar to their own - thereby reinforcing their existing beliefs and shielding them from diverse perspectives. There is a limit to regulation without innovation and by not having viable EU alternatives we have to accept cultural and ethical embedding from AI developed in other parts of the world.   

So where are we now? This first phase is over but since November 2022 a second phase of the AI revolution has started with the rise of Large Language Models (LLMs) such as OpenAI’s ChatGPT and Meta’s Llama 2. The economic and social impact of LLMs might be even larger than the first phase of AI represented by recommender systems. Recommender systems might dictate what you see from the internet world, but it does not massively replace humans. It does not teach humans. LLMs have the potential to do exactly that. And ChatGPT, Claude, Palm, Stability and the upcoming Gemini with their billion, sometimes trillion of parameters do not come from France, Hungary or Sweden. We might end up in a situation where these LLMs were trained to a large extent on European data, trained in the US but replace jobs in Europe. If we look at the top AI startups in the world (Figure 2 below) to project into the ecosystems of this second AI phase, the situation looks worrying for Europe to say the least. About 61% of the global funding is going to US companies and 17% goes to Chinese companies. Only 6% of the funding goes to EU27 start-ups. Patent applications over the past 7 years depict a similar picture. 34% of patents come from inventors based in the US, 22% from inventors based in China and only 11% from inventors based in EU27 countries.   

<iframe src="https://www.paballand.com/asg/esir/ai/startups.html" height="505" width="910" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" data-external="1"></iframe>      



