---
title: "ESB"
---

<style>
body {
text-align: justify}
</style>

## TECHNOLOGIES ANALYZED (EN)  
Optics and integrated photonics  
Quantum  
Green chemical production processes  
Biotechnology focused on molecules and cells  
Imagining technology  
(Opto)mechatronics (industrial systems/machines and equipment)  
Artificial intelligence (AI) and data  
Energy materials  
Semiconductors  
Cybersecurity  

## NOTE   
Data (RegPat) and methodology as usual, same as the report for the Dutch regions    
But we use PCT patents, instead of EPO (because of the international comparison). The Patent Cooperation Treaty (PCT) is an international treaty administered by the World Intellectual Property Organization (WIPO). It provides a unified procedure for filing patent applications to protect inventions in multiple countries. The EPO (European Patent Office) focuses on granting patents within European countries, making it ideal for protection within Europe, while the PCT system is designed for broader international coverage beyond Europe, offering a more global approach to patent protection.   
Period for international comparison = 2000-2023 (both included)   
Period for smart graphs, reldens, and complementarity maps = 2018-2023 (both included)   

## PATENTING OVER TIME FOR THE NL COMPARED WITH OTHER COUNTRIES  
https://www.paballand.com/asg/esb-2/competitiveness/beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/competitiveness/biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/competitiveness/cybersecurity.html  
https://www.paballand.com/asg/esb-2/competitiveness/energiematerialen.html  
https://www.paballand.com/asg/esb-2/competitiveness/groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/competitiveness/halfgeleiders.html  
https://www.paballand.com/asg/esb-2/competitiveness/kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/competitiveness/optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/competitiveness/optomechatronica.html  
https://www.paballand.com/asg/esb-2/competitiveness/quantum.html  
https://www.paballand.com/asg/esb-2/competitiveness/table.html  
https://www.paballand.com/asg/esb-2/competitiveness/table.csv    

## SMART SPEC GRAPHS   
https://www.paballand.com/asg/esb-2/smart/nl11.html  
https://www.paballand.com/asg/esb-2/smart/nl12.html  
https://www.paballand.com/asg/esb-2/smart/nl13.html  
https://www.paballand.com/asg/esb-2/smart/nl21.html  
https://www.paballand.com/asg/esb-2/smart/nl22.html  
https://www.paballand.com/asg/esb-2/smart/nl23.html  
https://www.paballand.com/asg/esb-2/smart/nl31.html  
https://www.paballand.com/asg/esb-2/smart/nl32.html  
https://www.paballand.com/asg/esb-2/smart/nl33.html  
https://www.paballand.com/asg/esb-2/smart/nl34.html  
https://www.paballand.com/asg/esb-2/smart/nl41.html  
https://www.paballand.com/asg/esb-2/smart/nl42.html  
https://www.paballand.com/asg/esb-2/smart/table.html  
https://www.paballand.com/asg/esb-2/smart/table.csv   

## RELATEDNESS DENSITY MAPS   
https://www.paballand.com/asg/esb-2/reldens/beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/reldens/biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/reldens/cybersecurity.html  
https://www.paballand.com/asg/esb-2/reldens/energiematerialen.html  
https://www.paballand.com/asg/esb-2/reldens/groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/reldens/halfgeleiders.html  
https://www.paballand.com/asg/esb-2/reldens/kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/reldens/optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/reldens/optomechatronica.html  
https://www.paballand.com/asg/esb-2/reldens/quantum.html  

## COMPLEMENTARITY MAPS   
https://www.paballand.com/asg/esb-2/complementarity/NL11-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL11-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL12-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL13-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL21-beeldvormingstechnologie.html    
https://www.paballand.com/asg/esb-2/complementarity/NL21-biotechnologie-gericht-op-moleculen-en-cellen.html    
https://www.paballand.com/asg/esb-2/complementarity/NL21-cybersecurity.html    
https://www.paballand.com/asg/esb-2/complementarity/NL21-energiematerialen.html    
https://www.paballand.com/asg/esb-2/complementarity/NL21-groene-chemische-productieprocessen.html    
https://www.paballand.com/asg/esb-2/complementarity/NL21-halfgeleiders.html    
https://www.paballand.com/asg/esb-2/complementarity/NL21-kunstmatige-intelligentie-en-data.html    
https://www.paballand.com/asg/esb-2/complementarity/NL21-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL21-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL21-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL22-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL23-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL31-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL32-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL33-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL34-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL41-quantum.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-beeldvormingstechnologie.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-biotechnologie-gericht-op-moleculen-en-cellen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-cybersecurity.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-energiematerialen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-groene-chemische-productieprocessen.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-halfgeleiders.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-kunstmatige-intelligentie-en-data.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-optica-en-geintegreerde-fotonica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-optomechatronica.html  
https://www.paballand.com/asg/esb-2/complementarity/NL42-quantum.html  

