---
title: "PROJECT S3 - DUTCH REGIONS"
---

<style>
body {
text-align: justify}
</style>

## DELIVERABLE 0

### TECHNOLOGY SPACE (36 TECHS; WIPO CLASSIFICATION) 
https://www.paballand.com/asg/nl/tech-space.html   

## DELIVERABLE 1   
*Methodological Note:*  
- Scope of work: treemaps and smart specialization graphs for technologies.   
- Treemaps indicate the number of patents, share, and rcas. Particularly useful for the dynamic analysis to see if a region decreased/increased its RCA into the most/least complex techs but also in the priorities previously identified.   
- Smart specialization graphs indicate relatedness density, complexity, and rcas.   
- Technological complexity is computed using the eigenvector reformulation from Hidalgo and Hausmann (2009) and adapted to patent data by Balland and Rigby (2017), also used by Balland and Boschma (2024) from SBS in the complexity traps report.   
- Data source: patent data from the OECD RegPat database; Aug. 2023 edition (latest available).      
- Tech level: prio (RIS priorities), wipo (36 categories), 3-digit and 4-digit CPCs.  
- Priorities are matched to a set of cpcs - identified exactly as in the previous report (see priority crosswalk below).  
- Spatial level: nuts1 and nuts2.    
- Time: 2018-2021 (2018, 2019, 2020 and 2021) and 2015-2018 (2015, 2016, 2017 and 2018).  
- Main article of reference: Balland, P.A., Boschma, R., Crespo, J. and Rigby, D. (2019) Smart Specialization policy in the EU: Relatedness, Knowledge Complexity and Regional Diversification, Regional Studies, 53 (9): 1252-1268.         

### 1.0 PRIORITY CROSSWALKS    

https://www.paballand.com/asg/nl/deliverable-1/prio/east-nl/prio.csv   
https://www.paballand.com/asg/nl/deliverable-1/prio/north-nl/prio.csv      
https://www.paballand.com/asg/nl/deliverable-1/prio/west-nl/prio.csv      
https://www.paballand.com/asg/nl/deliverable-1/prio/south-nl/prio.csv      

### 1.1 TREEMAPS  

#### EAST NL TREEMAPS  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/east-nl/east.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/east-nl/east.html 

https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/east-nl/east.html 

https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/east-nl/east.html 

#### NORTH NL TREEMAPS   

https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/north-nl/north.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/north-nl/north.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/north-nl/north.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/north-nl/north.html  


#### WEST NL TREEMAPS   

https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/west-nl/west.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/west-nl/west.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/west-nl/west.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/west-nl/west.html  

#### SOUTH NL TREEMAPS   

https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2015-2018/south-nl/south.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/4-digit/2018-2021/south-nl/south.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2015-2018/south-nl/south.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/3-digit/2018-2021/south-nl/south.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2015-2018/south-nl/south.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/wipo/2018-2021/south-nl/south.html  

https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2015-2018/south-nl/south.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/treemaps/prio/2018-2021/south-nl/south.html  

### 1.2 SMART SPEC GRAPHS  

#### EAST NL SMART SPEC GRAPHS  

https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/east-nl/east.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/east-nl/east.html 

https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/east-nl/east.html 

https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/east-nl/nl22.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/east-nl/east.html 

#### NORTH NL SMART SPEC GRAPHS  

https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/north-nl/north.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/north-nl/north.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/north-nl/north.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/north-nl/north.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/north-nl/nl13.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/north-nl/north.html  


#### WEST NL SMART SPEC GRAPHS  

https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/west-nl/west.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/west-nl/west.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/west-nl/west.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/west-nl/west.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/west-nl/nl23.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/west-nl/west.html  

#### SOUTH NL SMART SPEC GRAPHS  

https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2015-2018/south-nl/south.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/4-digit/2018-2021/south-nl/south.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2015-2018/south-nl/south.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/3-digit/2018-2021/south-nl/south.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2015-2018/south-nl/south.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/wipo/2018-2021/south-nl/south.html  

https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2015-2018/south-nl/south.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/south-nl/nl34.html  
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-1/smart/prio/2018-2021/south-nl/south.html  

## DELIVERABLE 2   
*Methodological Note:*  
- Scope of work: treemaps and smart specialization graphs for scientific fields.   
- Treemaps indicate the number of scientific publications, share, and rcas.     
- Smart specialization graphs indicate technological relatedness density, technological complexity (x axis and y axis are therefore identical to deliverable #1), and the size of bubbles is given by RCA in scientific fields.     
- Data source: scientific publications data from the OpenAlex database; last extracted Dec. 2023.      
- With 250 million publications OpenAlex is the largest dataset for academic publications in the world. OpenAlex replaced in 2021 the Microsoft Academic Graph.    
- Scientific level: prio (RIS priorities), wipo (36 categories).  
- Priorities and wipo categories are matched to OpenAlex scientific 'concepts'. Each scientific publication is classified into potentially multiple concepts, based on the title, abstract, and the title of the journal. The tagging is done using an automated AI classifier that was trained on Microsoft Academic Graph corpus (Read more about the methodology here: https://direct.mit.edu/qss/article/1/1/396/15572/Microsoft-Academic-Graph-When-experts-are-not). In total, there are about 65k concepts.  
- Concepts are organized as a tree strucutre, and we matched prio/wipo categories to concepts using a keyword search (variation and subset until match at the most aggregated level). Often the category (for instance biotech) perfectly matches the concept. Sometimes we had to decompose the wipo/prio category into sub-level concepts and re-aggregate (see priority crosswalk below, that also include wipo).    
- Spatial level: nuts1 and nuts2.    
- Time: 2023 and 2024.   
- Main article of reference: Balland, P.A. & Boschma, R. (2022) Do scientific capabilities in specific domains matter for technological diversification in European regions?, Research Policy, 51 (10): 1-12.    

### 2.0 PRIORITY CROSSWALKS    

https://www.paballand.com/asg/nl/deliverable-2/prio/east-nl/prio.csv   
https://www.paballand.com/asg/nl/deliverable-2/prio/north-nl/prio.csv      
https://www.paballand.com/asg/nl/deliverable-2/prio/west-nl/prio.csv      
https://www.paballand.com/asg/nl/deliverable-2/prio/south-nl/prio.csv      

### 2.1 TREEMAPS   

#### EAST NL TREEMAPS   

https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/east-nl/east.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/east-nl/nl22.html   

https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/east-nl/east.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/east-nl/nl21.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/east-nl/nl22.html   

#### NORTH NL TREEMAPS   

https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/north-nl/nl11.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/north-nl/nl12.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/north-nl/nl13.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/north-nl/north.html.  

https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/north-nl/nl11.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/north-nl/nl13.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/north-nl/north.html    

#### SOUTH NL TREEMAPS   

https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/south-nl/nl34.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/south-nl/nl41.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/south-nl/nl42.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/south-nl/south.html    

https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/south-nl/nl34.html    
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/south-nl/nl42.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/south-nl/south.html   

#### WEST NL TREEMAPS   

https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/west-nl/nl23.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/west-nl/nl32.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/wipo/west-nl/west.html   

https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/west-nl/nl23.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/west-nl/nl31.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/west-nl/nl32.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/west-nl/nl33.html   
https://www.paballand.com/asg/nl/deliverable-2/treemap/prio/west-nl/west.html   

### 2.2 SMART SPEC GRAPHS   

#### EAST NL SMART SPEC GRAPHS   

https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/east-nl/east.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/east-nl/nl21.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/east-nl/nl22.html  

https://www.paballand.com/asg/nl/deliverable-2/smart/prio/east-nl/east.html     
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/east-nl/nl21.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/east-nl/nl22.html  

#### NORTH NL SMART SPEC GRAPHS   

https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/north-nl/nl11.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/north-nl/nl13.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/north-nl/north.html    

https://www.paballand.com/asg/nl/deliverable-2/smart/prio/north-nl/nl11.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/north-nl/nl12.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/north-nl/nl13.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/north-nl/north.html   

#### SOUTH NL SMART SPEC GRAPHS   

https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/south-nl/nl34.html   
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/south-nl/nl42.html   
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/south-nl/south.html   

https://www.paballand.com/asg/nl/deliverable-2/smart/prio/south-nl/nl34.html   
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/south-nl/nl41.html   
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/south-nl/nl42.html   
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/south-nl/south.html  

#### WEST NL SMART SPEC GRAPHS   

https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/west-nl/nl23.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/west-nl/nl31.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/west-nl/nl33.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/wipo/west-nl/west.html    

https://www.paballand.com/asg/nl/deliverable-2/smart/prio/west-nl/nl23.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/west-nl/nl31.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/west-nl/nl32.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/west-nl/nl33.html    
https://www.paballand.com/asg/nl/deliverable-2/smart/prio/west-nl/west.html   

## DELIVERABLE 3   
*Methodological Note:*  
- This deliverable requires to put together data from the 4 regions, which has not been fully received yet.      

## DELIVERABLE 4   
*Methodological Note:*  
- Scope of work: complementarity maps for technologies.   
- Complementarity scores indicate the added relatedness density for any region-region-tech triad.    
- Added relatedness density algorithm as developed by Balland and Boschma (2021).   
- Data source: patent data from the OECD RegPat database; Aug. 2023 edition (latest available).      
- Tech level: prio (RIS priorities).  
- Spatial level: nuts1 and nuts2.    
- Time: 2018-2021 (2018, 2019, 2020 and 2021).  
- Main article of reference: Balland, P.A. and Boschma, R. (2021) Complementary Inter-Regional Linkages and Smart Specialization: an Empirical Study on European Regions, Regional Studies, 55 (6): 1059-1070.  

#### EAST NL COMPLEMENTARITY MAPS    

https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-agro-tech-smart-farming--vertical-farming.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-agro-tech-smart-farming.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-circulaire-en-natuur--inclusieve-landbouw.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-innovaties-voor-preventie--imaging.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-medtech-en-connected-health.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-nanotechnologie-en-fotonica--nanotechnologies.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-nanotechnologie-en-fotonica--photonics.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-protein-transition-and-food-technology.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-smart-industry-&-industrie-4.0--additive-manufacturing.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/east-smart-industry-&-industrie-4.0--autonomous-robots.html			
https://www.paballand.com/asg/nl/deliverable-4/east-nl/nl21-agro-tech-smart-farming--vertical-farming.html    
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-agro-tech-smart-farming.html                                        
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-circulaire-en-natuur--inclusieve-landbouw.html                      
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-innovaties-voor-preventie--imaging.html                             
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-medtech-en-connected-health.html                                    
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-nanotechnologie-en-fotonica--nanotechnologies.html                  
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-nanotechnologie-en-fotonica--photonics.html                         
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-protein-transition-and-food-technology.html                         
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-smart-industry-&-industrie-4.0--additive-manufacturing.html         
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL21-smart-industry-&-industrie-4.0--autonomous-robots.html              
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-agro-tech-smart-farming--vertical-farming.html                      
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-agro-tech-smart-farming.html                                        
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-circulaire-en-natuur--inclusieve-landbouw.html                      
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-innovaties-voor-preventie--imaging.html                             
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-medtech-en-connected-health.html                                    
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-nanotechnologie-en-fotonica--nanotechnologies.html                  
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-nanotechnologie-en-fotonica--photonics.html                         
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-protein-transition-and-food-technology.html                         
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-smart-industry-&-industrie-4.0--additive-manufacturing.html         
https://www.paballand.com/asg/nl/deliverable-4/east-nl/NL22-smart-industry-&-industrie-4.0--autonomous-robots.html     

#### NORTH NL COMPLEMENTARITY MAPS    

https://www.paballand.com/asg/nl/deliverable-4/north-nl/north-augmented-reality.html		
https://www.paballand.com/asg/nl/deliverable-4/north-nl/north-data-technology.html		
https://www.paballand.com/asg/nl/deliverable-4/north-nl/north-green-chemistry.html		
https://www.paballand.com/asg/nl/deliverable-4/north-nl/north-hydrogen-technology.html		
https://www.paballand.com/asg/nl/deliverable-4/north-nl/north-sensor-technology.html		
https://www.paballand.com/asg/nl/deliverable-4/north-nl/north-water-treatment-technology.html		
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL11-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL11-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL11-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL11-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL11-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL11-water-treatment-technology.html                                    
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL12-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL12-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL12-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL12-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL12-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL12-water-treatment-technology.html                                    
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL13-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL13-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL13-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL13-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL13-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-4/north-nl/NL13-water-treatment-technology.html             
 
#### SOUTH NL COMPLEMENTARITY MAPS    

https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-3d-printing-additive-productie.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-advanced-maintenance-cmms.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-artificial-intelligence.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-bio-landbouw.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-biosensors.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-carbon-capture.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-digitale-veiligheid.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-electrolizers-voor-power2molecule.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-elektrische-mobiliteit--battery-technologies.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-elektrische-mobiliteit--ev-charging-systems.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-energiebesparing-hardware-datacenters--photonic-memory.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-energieopslag--photovoltaic.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-gmo.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-hernieuwbare-energie--composieten.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-hernieuwbare-energie--windturbines.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-klimaatbeheersing.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-medtech-beeldvorming.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-nano-medicine.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-personalised-precision-medicine.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-precisielandbouw.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-recyclage.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-robotics--autonomous-robots.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-robotics--robots.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-robotisering-chirurgie-opafstand.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-smart-grids.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-super-labfoods.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-waste-water-treatment.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/south-zaadveredeling.html		
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL34-zaadveredeling.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL41-zaadveredeling.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-4/south-nl/NL42-zaadveredeling.html                    

#### WEST NL COMPLEMENTARITY MAPS    

https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/west-waterstof.html         
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL23-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL31-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL32-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-4/west-nl/NL33-waterstof.html  

## DELIVERABLE 5   
*Methodological note - see example here:*        
https://docs.google.com/spreadsheets/d/12DGiSsbDf6xyFQ1ZMWxFbRwP532WpAEn_2CpRU5NyR0/edit?usp=sharing    

#### 5.1 ACTUAL NB LINKS (BINARY, SO NO DOUBLE COUNTING IF MULTIPLE INV)
https://www.paballand.com/asg/nl/deliverable-5/links/NL41-artificial-intelligence.html    
https://www.paballand.com/asg/nl/deliverable-5/links/NL34-medtech-beeldvorming.html        
https://www.paballand.com/asg/nl/deliverable-5/links/east-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html        
https://www.paballand.com/asg/nl/deliverable-5/links/north-data-technology.html         

*My proposal to finalize the deliverable would be not only show the links of a given dutch region, but all links between all regions in a given priority as a network. This viz for instance is stunning, and shows connections in the field of AI:*    
https://www.paballand.com/asg/nl/deliverable-5/artificial-intelligence.html  

#### 5.2 LINKRCA
https://www.paballand.com/asg/nl/deliverable-5/link-rca/NL41-artificial-intelligence.html    
https://www.paballand.com/asg/nl/deliverable-5/link-rca/NL34-medtech-beeldvorming.html        
https://www.paballand.com/asg/nl/deliverable-5/link-rca/east-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html        
https://www.paballand.com/asg/nl/deliverable-5/link-rca/north-data-technology.html         

#### 5.3 EXPECTED
https://www.paballand.com/asg/nl/deliverable-5/expected/NL41-artificial-intelligence.html    
https://www.paballand.com/asg/nl/deliverable-5/expected/NL34-medtech-beeldvorming.html        
https://www.paballand.com/asg/nl/deliverable-5/expected/east-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html        
https://www.paballand.com/asg/nl/deliverable-5/expected/north-data-technology.html         

#### 5.4 HIDDEN POTENTIAL  (MAPS)
*Hidden potential = difference between ranking(complementarity) and ranking(link.rca), so higher is better, low or negative means tapped potential *       

#### EAST NL HIDDEN POTENTIAL  
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-agro-tech-smart-farming--vertical-farming-values.csv   	

https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-agro-tech-smart-farming--vertical-farming.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-agro-tech-smart-farming.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-circulaire-en-natuur--inclusieve-landbouw.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-innovaties-voor-preventie--imaging.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-medtech-en-connected-health.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nanotechnologie-en-fotonica--nanotechnologies.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nanotechnologie-en-fotonica--photonics.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-protein-transition-and-food-technology.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-smart-industry-&-industrie-4.0--additive-manufacturing.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-smart-industry-&-industrie-4.0--autonomous-robots.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/nl21-agro-tech-smart-farming--vertical-farming.html    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-agro-tech-smart-farming.html                                        
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-circulaire-en-natuur--inclusieve-landbouw.html                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-innovaties-voor-preventie--imaging.html                             
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-medtech-en-connected-health.html                                    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nanotechnologie-en-fotonica--nanotechnologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nanotechnologie-en-fotonica--photonics.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-protein-transition-and-food-technology.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-smart-industry-&-industrie-4.0--additive-manufacturing.html         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-smart-industry-&-industrie-4.0--autonomous-robots.html              
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-agro-tech-smart-farming--vertical-farming.html                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-agro-tech-smart-farming.html                                        
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-circulaire-en-natuur--inclusieve-landbouw.html                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-innovaties-voor-preventie--imaging.html                             
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-medtech-en-connected-health.html                                    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nanotechnologie-en-fotonica--nanotechnologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nanotechnologie-en-fotonica--photonics.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-protein-transition-and-food-technology.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-smart-industry-&-industrie-4.0--additive-manufacturing.html         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-smart-industry-&-industrie-4.0--autonomous-robots.html     

#### NORTH NL HIDDEN POTENTIAL  

https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-augmented-reality.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-data-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-green-chemistry.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-hydrogen-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-sensor-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-water-treatment-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-water-treatment-technology.html                                    
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-water-treatment-technology.html                                    
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-water-treatment-technology.html             
 
#### SOUTH NL HIDDEN POTENTIAL  

https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-3d-printing-additive-productie.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-advanced-maintenance-cmms.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-artificial-intelligence.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-bio-landbouw.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-biosensors.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-carbon-capture.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-digitale-veiligheid.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-electrolizers-voor-power2molecule.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-elektrische-mobiliteit--battery-technologies.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-elektrische-mobiliteit--ev-charging-systems.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-energiebesparing-hardware-datacenters--photonic-memory.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-energieopslag--photovoltaic.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-gmo.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-hernieuwbare-energie--composieten.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-hernieuwbare-energie--windturbines.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-klimaatbeheersing.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-medtech-beeldvorming.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-nano-medicine.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-personalised-precision-medicine.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-precisielandbouw.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-recyclage.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotics--autonomous-robots.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotics--robots.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotisering-chirurgie-opafstand.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-smart-grids.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-super-labfoods.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-waste-water-treatment.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-zaadveredeling.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-zaadveredeling.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-zaadveredeling.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-zaadveredeling.html                    

#### WEST NL HIDDEN POTENTIAL  

https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-waterstof.html         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-waterstof.html    

#### 5.3 NETWORK ANALYSIS  

#### EAST NL HIDDEN POTENTIAL  

https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-agro-tech-smart-farming--vertical-farming.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-agro-tech-smart-farming.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-circulaire-en-natuur--inclusieve-landbouw.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-innovaties-voor-preventie--imaging.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-medtech-en-connected-health.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nanotechnologie-en-fotonica--nanotechnologies.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nanotechnologie-en-fotonica--photonics.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-protein-transition-and-food-technology.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-smart-industry-&-industrie-4.0--additive-manufacturing.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-smart-industry-&-industrie-4.0--autonomous-robots.html			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/nl21-agro-tech-smart-farming--vertical-farming.html    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-agro-tech-smart-farming.html                                        
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-circulaire-en-natuur--inclusieve-landbouw.html                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-innovaties-voor-preventie--imaging.html                             
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-medtech-en-connected-health.html                                    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nanotechnologie-en-fotonica--nanotechnologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nanotechnologie-en-fotonica--photonics.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-protein-transition-and-food-technology.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-smart-industry-&-industrie-4.0--additive-manufacturing.html         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-smart-industry-&-industrie-4.0--autonomous-robots.html              
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-agro-tech-smart-farming--vertical-farming.html                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-agro-tech-smart-farming.html                                        
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-circulaire-en-natuur--inclusieve-landbouw.html                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-innovaties-voor-preventie--imaging.html                             
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-medtech-en-connected-health.html                                    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nanotechnologie-en-fotonica--nanotechnologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nanotechnologie-en-fotonica--photonics.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials.html
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-protein-transition-and-food-technology.html                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-smart-industry-&-industrie-4.0--additive-manufacturing.html         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-smart-industry-&-industrie-4.0--autonomous-robots.html     

#### NORTH NL HIDDEN POTENTIAL  

https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-augmented-reality.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-data-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-green-chemistry.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-hydrogen-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-sensor-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-water-treatment-technology.html		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-water-treatment-technology.html                                    
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-water-treatment-technology.html                                    
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-augmented-reality.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-data-technology.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-green-chemistry.html                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-hydrogen-technology.html                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-sensor-technology.html                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-water-treatment-technology.html             
 
#### SOUTH NL HIDDEN POTENTIAL  

https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-3d-printing-additive-productie.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-advanced-maintenance-cmms.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-artificial-intelligence.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-bio-landbouw.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-biosensors.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-carbon-capture.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-digitale-veiligheid.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-electrolizers-voor-power2molecule.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-elektrische-mobiliteit--battery-technologies.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-elektrische-mobiliteit--ev-charging-systems.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-energiebesparing-hardware-datacenters--photonic-memory.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-energieopslag--photovoltaic.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-gmo.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-hernieuwbare-energie--composieten.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-hernieuwbare-energie--windturbines.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-klimaatbeheersing.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-medtech-beeldvorming.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-nano-medicine.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-personalised-precision-medicine.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-precisielandbouw.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-recyclage.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotics--autonomous-robots.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotics--robots.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotisering-chirurgie-opafstand.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-smart-grids.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-super-labfoods.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-waste-water-treatment.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-zaadveredeling.html		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-zaadveredeling.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-zaadveredeling.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-3d-printing-additive-productie.html                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-advanced-maintenance-cmms.html                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-artificial-intelligence.html                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-bio-landbouw.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-biosensors.html                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-carbon-capture.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-digitale-veiligheid.html                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-electrolizers-voor-power2molecule.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-elektrische-mobiliteit--battery-technologies.html                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-elektrische-mobiliteit--ev-charging-systems.html                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-energiebesparing-hardware-datacenters--photonic-memory.html        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-energieopslag--photovoltaic.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-gmo.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-hernieuwbare-energie--composieten.html                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-hernieuwbare-energie--windturbines.html                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-klimaatbeheersing.html                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-medtech-beeldvorming.html                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-nano-medicine.html                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-personalised-precision-medicine.html                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-precisielandbouw.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-recyclage.html                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotics--autonomous-robots.html                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotics--robots.html                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotisering-chirurgie-opafstand.html                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-smart-grids.html                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-super-labfoods.html                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-waste-water-treatment.html                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-zaadveredeling.html                    

#### WEST NL HIDDEN POTENTIAL  

https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-waterstof.html         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-waterstof.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-aerospace.html                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-batterietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-chemische-recycling.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-circulair-bouwen.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-co2-vrije-elektriciteit.html                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-cybersecurity.html                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-defensietechnologie.html                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-e-health.html                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-engineering-fabrication--additive-manufacturing.html                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-engineering-fabrication--autonomous-robots.html                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-hergebruik-plastic.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-imaging.html                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-innovatief-waterbeheer.html                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-klimaatneutrale-landbouw.html                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-kringloop-landbouw.html                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-life-sciences--biotechnology.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-nano.html                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-regeneratieve-geneeskunde.html                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-slimme-mobiliteit.html                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-valorisatie-deltatechnologie.html                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-vertical-farming.html                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-waterstof.html    

#### 5.5 HIDDEN POTENTIAL  (TABLES)
*Hidden potential = difference between ranking(complementarity) and ranking(link.rca), so higher is better, low or negative means tapped potential *       

#### EAST NL HIDDEN POTENTIAL  (TABLES)   

https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-agro-tech-smart-farming--vertical-farming-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-agro-tech-smart-farming-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-circulaire-en-natuur--inclusieve-landbouw-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-innovaties-voor-preventie--imaging-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-medtech-en-connected-health-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nanotechnologie-en-fotonica--nanotechnologies-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nanotechnologie-en-fotonica--photonics-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-protein-transition-and-food-technology-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-smart-industry-&-industrie-4.0--additive-manufacturing-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/east-smart-industry-&-industrie-4.0--autonomous-robots-values.csv			
https://www.paballand.com/asg/nl/deliverable-5/east-nl/nl21-agro-tech-smart-farming--vertical-farming-values.csv    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-agro-tech-smart-farming-values.csv                                        
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-circulaire-en-natuur--inclusieve-landbouw-values.csv                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-innovaties-voor-preventie--imaging-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-medtech-en-connected-health-values.csv                                    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nanotechnologie-en-fotonica--nanotechnologies-values.csv                  
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nanotechnologie-en-fotonica--photonics-values.csv                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials-values.csv
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-protein-transition-and-food-technology-values.csv                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-smart-industry-&-industrie-4.0--additive-manufacturing-values.csv         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL21-smart-industry-&-industrie-4.0--autonomous-robots-values.csv              
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-agro-tech-smart-farming--vertical-farming-values.csv                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-agro-tech-smart-farming-values.csv                                        
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-circulaire-en-natuur--inclusieve-landbouw-values.csv                      
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-innovaties-voor-preventie--imaging-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-medtech-en-connected-health-values.csv                                    
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nanotechnologie-en-fotonica--nanotechnologies-values.csv                  
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nanotechnologie-en-fotonica--photonics-values.csv                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-nieuwe-duurzame-en-geavanceerde-materialen--composite-materials-values.csv
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-protein-transition-and-food-technology-values.csv                         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-smart-industry-&-industrie-4.0--additive-manufacturing-values.csv         
https://www.paballand.com/asg/nl/deliverable-5/east-nl/NL22-smart-industry-&-industrie-4.0--autonomous-robots-values.csv     

#### NORTH NL HIDDEN POTENTIAL  (TABLES)    

https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-augmented-reality-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-data-technology-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-green-chemistry-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-hydrogen-technology-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-sensor-technology-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/north-water-treatment-technology-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-augmented-reality-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-data-technology-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-green-chemistry-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-hydrogen-technology-values.csv                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-sensor-technology-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL11-water-treatment-technology-values.csv                                    
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-augmented-reality-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-data-technology-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-green-chemistry-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-hydrogen-technology-values.csv                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-sensor-technology-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL12-water-treatment-technology-values.csv                                    
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-augmented-reality-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-data-technology-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-green-chemistry-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-hydrogen-technology-values.csv                                           
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-sensor-technology-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/north-nl/NL13-water-treatment-technology-values.csv             
 
#### SOUTH NL HIDDEN POTENTIAL (TABLES)    

https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-3d-printing-additive-productie-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-advanced-maintenance-cmms-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-artificial-intelligence-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-bio-landbouw-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-biosensors-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-carbon-capture-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-digitale-veiligheid-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-electrolizers-voor-power2molecule-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-elektrische-mobiliteit--battery-technologies-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-elektrische-mobiliteit--ev-charging-systems-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-energiebesparing-hardware-datacenters--photonic-memory-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-energieopslag--photovoltaic-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-gmo-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-hernieuwbare-energie--composieten-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-hernieuwbare-energie--windturbines-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-klimaatbeheersing-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-medtech-beeldvorming-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-nano-medicine-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-personalised-precision-medicine-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-precisielandbouw-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-recyclage-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotics--autonomous-robots-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotics--robots-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-robotisering-chirurgie-opafstand-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-smart-grids-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-super-labfoods-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-waste-water-treatment-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/south-zaadveredeling-values.csv		
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-3d-printing-additive-productie-values.csv                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-advanced-maintenance-cmms-values.csv                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-artificial-intelligence-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-bio-landbouw-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-biosensors-values.csv                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-carbon-capture-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-digitale-veiligheid-values.csv                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-electrolizers-voor-power2molecule-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-elektrische-mobiliteit--battery-technologies-values.csv                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-elektrische-mobiliteit--ev-charging-systems-values.csv                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-energiebesparing-hardware-datacenters--photonic-memory-values.csv        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-energieopslag--photovoltaic-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-gmo-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-hernieuwbare-energie--composieten-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-hernieuwbare-energie--windturbines-values.csv                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-klimaatbeheersing-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-medtech-beeldvorming-values.csv                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-nano-medicine-values.csv                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-personalised-precision-medicine-values.csv                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-precisielandbouw-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-recyclage-values.csv                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotics--autonomous-robots-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotics--robots-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-robotisering-chirurgie-opafstand-values.csv                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-smart-grids-values.csv                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-super-labfoods-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-waste-water-treatment-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL34-zaadveredeling-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-3d-printing-additive-productie-values.csv                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-advanced-maintenance-cmms-values.csv                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-artificial-intelligence-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-bio-landbouw-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-biosensors-values.csv                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-carbon-capture-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-digitale-veiligheid-values.csv                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-electrolizers-voor-power2molecule-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-elektrische-mobiliteit--battery-technologies-values.csv                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-elektrische-mobiliteit--ev-charging-systems-values.csv                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-energiebesparing-hardware-datacenters--photonic-memory-values.csv        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-energieopslag--photovoltaic-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-gmo-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-hernieuwbare-energie--composieten-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-hernieuwbare-energie--windturbines-values.csv                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-klimaatbeheersing-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-medtech-beeldvorming-values.csv                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-nano-medicine-values.csv                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-personalised-precision-medicine-values.csv                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-precisielandbouw-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-recyclage-values.csv                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotics--autonomous-robots-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotics--robots-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-robotisering-chirurgie-opafstand-values.csv                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-smart-grids-values.csv                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-super-labfoods-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-waste-water-treatment-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL41-zaadveredeling-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-3d-printing-additive-productie-values.csv                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-advanced-maintenance-cmms-values.csv                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-artificial-intelligence-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-bio-landbouw-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-biosensors-values.csv                                                    
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-carbon-capture-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-digitale-veiligheid-values.csv                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-electrolizers-voor-power2molecule-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-elektrische-mobiliteit--battery-technologies-values.csv                  
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-elektrische-mobiliteit--ev-charging-systems-values.csv                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-energiebesparing-hardware-datacenters--photonic-memory-values.csv        
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-energieopslag--photovoltaic-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-gmo-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-hernieuwbare-energie--composieten-values.csv                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-hernieuwbare-energie--windturbines-values.csv                            
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-klimaatbeheersing-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-medtech-beeldvorming-values.csv                                          
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-nano-medicine-values.csv                                                 
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-personalised-precision-medicine-values.csv                               
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-precisielandbouw-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-recyclage-values.csv                                                     
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotics--autonomous-robots-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotics--robots-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-robotisering-chirurgie-opafstand-values.csv                              
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-smart-grids-values.csv                                                   
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-super-labfoods-values.csv                                                
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-waste-water-treatment-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/south-nl/NL42-zaadveredeling-values.csv                    

#### WEST NL HIDDEN POTENTIAL (TABLES)    

https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-aerospace-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-batterietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-chemische-recycling-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-circulair-bouwen-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-co2-vrije-elektriciteit-values.csv                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-cybersecurity-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-defensietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-e-health-values.csv                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-engineering-fabrication--additive-manufacturing-values.csv                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-engineering-fabrication--autonomous-robots-values.csv                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-hergebruik-plastic-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-imaging-values.csv                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-innovatief-waterbeheer-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-klimaatneutrale-landbouw-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-kringloop-landbouw-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-life-sciences--biotechnology-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-nano-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-regeneratieve-geneeskunde-values.csv                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-slimme-mobiliteit-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-valorisatie-deltatechnologie-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-vertical-farming-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/west-waterstof-values.csv         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-aerospace-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-batterietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-chemische-recycling-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-circulair-bouwen-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-co2-vrije-elektriciteit-values.csv                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-cybersecurity-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-defensietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-e-health-values.csv                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-engineering-fabrication--additive-manufacturing-values.csv                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-engineering-fabrication--autonomous-robots-values.csv                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-hergebruik-plastic-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-imaging-values.csv                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-innovatief-waterbeheer-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-klimaatneutrale-landbouw-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-kringloop-landbouw-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-life-sciences--biotechnology-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-nano-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-regeneratieve-geneeskunde-values.csv                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-slimme-mobiliteit-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-valorisatie-deltatechnologie-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-vertical-farming-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL23-waterstof-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-aerospace-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-batterietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-chemische-recycling-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-circulair-bouwen-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-co2-vrije-elektriciteit-values.csv                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-cybersecurity-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-defensietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-e-health-values.csv                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-engineering-fabrication--additive-manufacturing-values.csv                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-engineering-fabrication--autonomous-robots-values.csv                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-hergebruik-plastic-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-imaging-values.csv                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-innovatief-waterbeheer-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-klimaatneutrale-landbouw-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-kringloop-landbouw-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-life-sciences--biotechnology-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-nano-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-regeneratieve-geneeskunde-values.csv                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-slimme-mobiliteit-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-valorisatie-deltatechnologie-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-vertical-farming-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL31-waterstof-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-aerospace-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-batterietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-chemische-recycling-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-circulair-bouwen-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-co2-vrije-elektriciteit-values.csv                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-cybersecurity-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-defensietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-e-health-values.csv                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-engineering-fabrication--additive-manufacturing-values.csv                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-engineering-fabrication--autonomous-robots-values.csv                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-hergebruik-plastic-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-imaging-values.csv                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-innovatief-waterbeheer-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-klimaatneutrale-landbouw-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-kringloop-landbouw-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-life-sciences--biotechnology-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-nano-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-regeneratieve-geneeskunde-values.csv                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-slimme-mobiliteit-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-valorisatie-deltatechnologie-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-vertical-farming-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL32-waterstof-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-aerospace-values.csv                                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-batterietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-chemische-recycling-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-circulair-bouwen-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-co2-vrije-elektriciteit-values.csv                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-cybersecurity-values.csv                                                  
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-defensietechnologie-values.csv                                            
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-e-health-values.csv                                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-engineering-fabrication--additive-manufacturing-values.csv                
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-engineering-fabrication--autonomous-robots-values.csv                     
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-hergebruik-plastic-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-imaging-values.csv                                                        
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-innovatief-waterbeheer-values.csv                                         
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-klimaatneutrale-landbouw-values.csv                                       
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-kringloop-landbouw-values.csv                                             
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-life-sciences--biotechnology-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-nano-values.csv                                                           
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-regeneratieve-geneeskunde-values.csv                                      
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-slimme-mobiliteit-values.csv                                              
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-valorisatie-deltatechnologie-values.csv                                   
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-vertical-farming-values.csv                                               
https://www.paballand.com/asg/nl/deliverable-5/west-nl/NL33-waterstof-values.csv    

## DELIVERABLE 6   
*Proposal from Ron: Policy recommendations based on these results. A draft of the report will be delivered in mid-December 2023. Final report will be delivered at the end of January 2024*  


