---
title: "State of Open Source AI 2024"
---

<style>
body {
text-align: justify}
</style>

### SNAPHOT OF 2024 (TREEMAPS) 
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/author-author-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/author-tag-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/author-tag-likes-top-1000.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/author-tag-likes.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/id-tag-likes-top-100 copy.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/id-tag-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/model-tag-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/model-tag-likes.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/pipeline_tag-tag-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/_archives/pipeline_tag-tag-likes-top-1000.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/country_model_downloads.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/country_model_likes.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/_archives/author-tag-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/_archives/author-tag-downloads-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/_archives/author-tag-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/_archives/stacked-author-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/_archives/stacked-author-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/_archives/stacked-author-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/_archives/stacked-author-top-100pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-100pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-200-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-200-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-200-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/stacked-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/treemap-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/treemap-downloads-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/author/treemap-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/_archives/library-tag-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/_archives/library-tag-downloads-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/_archives/library-tag-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/_archives/stacked-library-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/_archives/stacked-library-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/_archives/stacked-library-top-100-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/_archives/stacked-library-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/stacked-likes-top-200-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/stacked-likes-top-200-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/stacked-likes-top-200-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/library/stacked-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/_archives/license-tag-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/_archives/license-tag-downloads-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/_archives/license-tag-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/_archives/stacked-license-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/_archives/stacked-license-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/_archives/stacked-license-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/_archives/stacked-license-top-100pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/stacked-likes-top-200-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/stacked-likes-top-200-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/stacked-likes-top-200-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/license/stacked-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/1-1-model-tag-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/1-2-model-tag-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/1-3-model-tag-downloads-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/2-1-stacked-model-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/2-2-stacked-model-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/3-1-geomap.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/4-network.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/model-tag-downloads_all_time-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/model-tag-downloads-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/model-tag-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/stacked-model-top-100-cumulative-black-forest.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/stacked-model-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/stacked-model-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/stacked-model-top-100-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/_archives/stacked-model-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/treemap-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/treemap-downloads_past_30_days-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/treemap-downloads-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/treemap-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/model/treemap-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/_archive/pipeline_tag-tag-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/_archive/pipeline_tag-tag-downloads-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/_archive/pipeline_tag-tag-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/_archive/stacked-pipeline_tag-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/_archive/stacked-pipeline_tag-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/_archive/stacked-pipeline_tag-top-100-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/_archive/stacked-pipeline_tag-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/stacked-likes-top-200-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/stacked-likes-top-200-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/stacked-likes-top-200-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/stacked-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/treemap-downloads_all_time-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/pipeline/treemap-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/model-tag-likes-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-likes-top-200-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-likes-top-200-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-likes-top-200-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-likes-top-200.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-tag-top-100-cumulative-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-tag-top-100-cumulative.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-tag-top-100-pc.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/model/tag/stacked-tag-top-100.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/org_model_downloads.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/org_model_likes.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/stacked.html
/Users/pierre-alex/Dropbox/PABalland.github.io/hf/api/urban.html

