---
title: "The Artificial Intelligence Revolution"
author: '[Prof. Pierre-Alexandre Balland](https://www.paballand.com/)'
output:
  html_document:
    df_print: paged
---

<style>
body {
text-align: justify}
</style>

### Course description  
The AI revolution is rapidly taking the world by storm. We can only be mesmerized by how quickly intelligent machines have learned to drive cars, read lung scans, or predict what we will want to listen, watch, or buy better than any human. This extraordinary technology is still in its very infancy but has already driven most of recent stock market growth while disrupting entire industries and rendering high-status skills and occupations completely obsolete. In this class, Professor Balland provides an entry point for high school students to understand and thrive in this new AI world. It addresses the macro-level impact of AI on the economy, introduces the technical principles of modern AI algorithms, and invites students to critically think about the skills and values they need for a world so different from the ones our education system was designed for. The class does not require specific mathematical or programming skills - just a deep interest in how AI will shape our future.          

### Meet the instructor    
[Pierre-Alexandre Balland](https://www.paballand.com/) is a [French economist](https://scholar.google.com/citations?user=ORZg_McAAAAJ&hl=en&oi=ao) and one of Europe's leading experts on complex systems, the future of cities, artificial intelligence and blockchain technologies. He is a [Professor](https://www.uu.nl/staff/PMABalland/Profile) at [Utrecht University](https://www.uu.nl/en) and previously held positions at [MIT](https://www.media.mit.edu/people/balland/overview/) and  [UCLA](https://www.ucla.edu/). He is a Visiting Professor at the [Center for Collective Learning](https://centerforcollectivelearning.org/) of the [Artificial and Natural Intelligence Toulouse Institute](https://en.univ-toulouse.fr/aniti) and a research fellow at the [Center for Complex Systems Studies](https://www.uu.nl/en/research/centre-for-complex-systems-studies-ccss). Prof. Balland is also a high-level policy expert that  currently serves in the [ESIR](https://ec.europa.eu/info/research-and-innovation/strategy/support-policy-making/support-eu-research-and-innovation-policy-making/esir_en) group to advise the European Commission on innovation policy.    

The teaching assistant for this class is Caltech computer science grad student [Chanukya Malla](malla.chanukya@alumni.caltech.edu). Chanu will supervise students' assignments and he can be contacted by email at this address: malla.chanukya@alumni.caltech.edu.        

### What students will learn  
1. The real-world problems AI is solving  
2. How AI creates a monopoly and a winner-takes-all society  
3. What AI cannot predict - and the increasing importance of human wisdom  
4. High-level understanding of machine learning, deep learning & network science  
5. The building blocks of AI systems: network data structures  
6. How to transform data into meaningful, actionable insights  
7. How to build an AI recommendation system to solve a real-world problem  

### Structure of the class      
The class consists of four teaching moments: two lectures, one tutorial, and one final pitch deck presentation. The first lecture introduces the impact of AI on our society and allows students to understand the business and societal problems that AI can solve. The second lecture is more technical in nature and discusses the underlying principles of modern AI algorithms. The tutorial connects the first and second lectures by inviting students to build a recommendation system to solve a real-world problem of their choice. During the last class, students will have the opportunity to present their big idea and receive feedback. Students can join the class by following this [zoom link](https://us02web.zoom.us/j/87425789828?pwd=dUtlSWpIbjVHdFdoSDRzZThEZy9QUT09).      

### Course Schedule  

|   Activity  |      Day |   Date  |      Time   | Location |     Lecturer     |
|:-----------:|:--------:|:-------:|:-----------:|:--------:|:----------------:|
|Lecture 1    | Sunday   | Sept. 5 | 09:00-10:00 |  Online  |  Prof. Balland   |
|Lecture 2    | Sunday   | Sept. 19| 09:00-10:00 |  Online  |  Prof. Balland   |
|Tutorial     | Sunday   | Oct. 3  | 09:00-10:00 |  Online  |  Prof. Balland   |
|Presentations| Sunday   | Oct. 17 | 09:00-10:00 |  Online  |  Prof. Balland   |   

##### **Lecture 1: Artificial intelligence and human society**  [SLIDES TBA](.pdf)   
*Topics covered*  
- Overview of class   
- Scope and limits of the AI revolution   
- Key applications of AI for business and society   
- Predicting in a complex world   
- Winners and losers of the AI revolution     

*Homework*   
This lecture is coupled with 1 hour of TA office hours. Students will have to write a 1000-word essay on a macro-level impact of AI on society or a specific use case of AI.     

##### **Lecture 2: Artificial intelligence tools and principles**  [SLIDES TBA](.pdf)   
*Topics covered*  
- What AI is and what AI is not   
- AI, network science, ML and DL        
- The data matrix being key AI applications          
- Talking to your computer: demystifying programming language   
- Working principles of recommendation systems   

*Homework*   
This lecture is coupled with 2 hours of TA office hours. Students will have to do a computer lab assignment in R/Python that will help them to understand the working principles of a simple ML recommendation system.     

##### **Tutorial: Pitching your big idea**  [SLIDES TBA](.pdf)   
*Topics covered*  
- Introduction to the VC/start-up world  
- How to design your AI solution     
- Key elements of a pitch deck      
- Tips on communication & delivery   
- First discussion of students' presentation topics        

*Homework*   
This tutorial is coupled with 3 hours of TA office hours. Students will get feedback on building a recommendation system to solve a real-world problem of their choice and building the pitch deck to be presented during the final session. The deck should include a R/python script that reflect the main working principle of the recommendation system.        

### Readings  
There is no mandatory reading for these class but the following books, papers, and newspapers make excellent companions:   
- [The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies](https://www.amazon.com/Second-Machine-Age-Prosperity-Technologies/dp/0393350649) by Erik Brynjolfsson & Andrew McAfee    
- [Prediction Machines: The Simple Economics of Artificial Intelligence](https://www.amazon.com/Prediction-Machines-Economics-Artificial-Intelligence/dp/1633695670) by Ajay Agrawal, Joshua Gans & Avi Goldfarb        
- [AI Superpowers: China, Silicon Valley, And The New World Order](https://www.amazon.com/AI-Superpowers-China-Silicon-Valley/dp/132854639X) by Kai-Fu Lee    
- LeCun, Yann, Yoshua Bengio, and Geoffrey Hinton (2015) [Deep learning](https://www.nature.com/articles/nature14539), *Nature* (you don't have to understand it all - just skim through it)  
- Pierre-Alexandre Balland, Cristian Jara-Figueroa, Sergio G. Petralia, Mathieu P. A. Steijn, David L. Rigby & César A. Hidalgo (2020) [Complex economic activities concentrate in large cities](https://www.nature.com/articles/s41562-019-0803-3#:~:text=Complex%20economic%20activities%2C%20such%20as,as%20apparel%20or%20paper%20manufacturing.), *Nature Human Behavior*     
- Amazon's description of their [collaborative filtering AI system](https://www.amazon.science/the-history-of-amazons-recommendation-algorithm)    
- [Why data is the most valuable resource](https://www.economist.com/leaders/2017/05/06/the-worlds-most-valuable-resource-is-no-longer-oil-but-data) according to *The Economist*     

