---
title: "ChatGPT & the Artificial Intelligence Revolution"
author: '[Prof. Pierre-Alexandre Balland](https://www.paballand.com/)'
output:
  html_document:
    df_print: paged
---

<style>
body {
text-align: justify}
</style>

### Course description  
The AI revolution is rapidly changing the world as we know it - and ChatGPT is leading the way. In just two months after launch, it had already reached 100 million users and is seen by many experts as a potential game-changer when it comes to how humans live, learn, and work. This class is designed to help students take full advantage of ChatGPT and the AI revolution more broadly.   

Most of us recognize that artificial intelligence has advanced to the point of being able to do things like driving cars, reading lung scans, or making better predictions about what we want to watch or buy than humans. But how does this remarkable technology work? How can it cause disruption in entire industries and render some high-level skills and occupations useless? What topics do students need to learn in order to succeed in an AI-dominated world?   

In this class, Professor Balland provides high school students with the tools they need to understand and excel in this new AI world. It covers not only the basics of ChatGPT, but also tackles the macro-level implications of AI on the economy. Technical principles of modern AI algorithms will be introduced and students will be encouraged to think critically about the skills and values that are needed to survive in a world vastly different from what our current educational system prepares us for. No specific math or programming experience is necessary - just a deep curiosity about how ChatGPT-like models and AI will affect our future.            

### Meet the instructor    
[Pierre-Alexandre Balland](https://www.paballand.com/) is a [French economist](https://scholar.google.com/citations?user=ORZg_McAAAAJ&hl=en&oi=ao) and one of Europe's leading experts on complex systems, the future of cities, artificial intelligence and blockchain technologies. He is a [Professor](https://www.uu.nl/staff/PMABalland/Profile) at [Utrecht University](https://www.uu.nl/en) and previously held positions at [MIT](https://www.media.mit.edu/people/balland/overview/) and  [UCLA](https://www.ucla.edu/). He is a Visiting Professor at the [Center for Collective Learning](https://centerforcollectivelearning.org/) of the [Artificial and Natural Intelligence Toulouse Institute](https://en.univ-toulouse.fr/aniti) and a research fellow at the [Center for Complex Systems Studies](https://www.uu.nl/en/research/centre-for-complex-systems-studies-ccss). Prof. Balland is also a high-level policy expert that  currently serves in the [ESIR](https://ec.europa.eu/info/research-and-innovation/strategy/support-policy-making/support-eu-research-and-innovation-policy-making/esir_en) group to advise the European Commission on innovation policy.    

The teaching assistant for this class is Caltech computer science grad student [Chanukya Malla](malla.chanukya@alumni.caltech.edu). Chanu will supervise students' assignments and he can be contacted by email at this address: malla.chanukya@alumni.caltech.edu.        

### What students will learn   
1. What ChatGPT is and how to use it to solve big problems and be more productive    
2. The real-world problems AI is solving  
3. How AI creates a monopoly and a winner-takes-all society  
4. What AI cannot predict - and the increasing importance of human wisdom  
5. High-level understanding of machine learning, deep learning & network science  
6. The building blocks of AI systems: network data structures  
7. How to transform data into meaningful, actionable insights  
8. How to build an AI recommendation system to solve a real-world problem  

### Structure of the class      
The class consists of four distinct components: two lectures, one tutorial, and a final pitch deck presentation. The first lecture introduces ChatGPT and the sweeping impact of AI on our modern society, giving students an overview of the business problems that AI can help to solve. Then, the second lecture dives into the technical aspects of AI algorithms. In the tutorial, students are invited to use ChatGPT to build a recommendation system for a real-world problem of their choice, as well as market research, and creating a slide deck. During the last class, students will have the opportunity to present their big idea and receive feedback. Students can join the class by following this [zoom link](https://us02web.zoom.us/j/85776303655?pwd=d1VrNm1GM3E0ZmpVR3h2VUkwUWMzZz09). The Meeting ID is 857 7630 3655 with passcode: 204574.   

### Course Schedule  

|   Activity  |      Day |   Date  |      Time      | Location |     Lecturer     |
|:-----------:|:--------:|:-------:|:--------------:|:--------:|:----------------:|
|Lecture 1    | Thursday | June 23 |10:30-11:30 (AM)|  Online  |  Prof. Balland   |
|Lecture 2    | Thursday | June 30 |10:30-11:30 (AM)|  Online  |  Prof. Balland   |
|Tutorial     | Thursday | July 14 |10:30-11:30 (AM)|  Online  |  Prof. Balland   |
|Presentations| Thursday | July 28 |10:30-11:30 (AM)|  Online  |  Prof. Balland   |  

##### **Lecture 1: ChatGPT, Artificial intelligence and human society**       
*Topics covered*  
- Overview of class   
- Scope and limits of the AI revolution   
- What is ChatGPT and is it a tipping point for AI?
- Key applications of AI for business and society   
- Predicting in a complex world   
- Winners and losers of the AI revolution     

*Homework*   
This lecture is coupled with 1 hour of TA office hours. Students will have to write a 1000-word essay on a macro-level impact of AI on society or a specific use case of AI. This essay will be written in pair with ChatGPT and students will be evaluated based on their prompts, iterations & critical assessment of the AI input.         

##### **Lecture 2: Artificial intelligence tools and principles**      
*Topics covered*  
- What AI is and what AI is not   
- AI, network science, ML and DL        
- The data matrix behind key AI applications          
- Talking to your computer: demystifying programming language   
- Working principles of recommendation systems   

*Homework*   
This lecture is coupled with 2 hours of TA office hours. Students will have to do a computer lab assignment in R/Python that will help them to understand the working principles of a simple ML recommendation system. ChatGPT can be used for pair-programming.         

##### **Tutorial: Using ChatGPT to sharpen & pitch your big idea**       
*Topics covered*  
- Introduction to the VC/start-up world  
- How can ChatGPT help   
- How to design your AI solution     
- Key elements of a pitch deck      
- Tips on communication & delivery   
- First discussion of students' presentation topics        

*Homework*   
This tutorial is coupled with 3 hours of TA office hours. Students will get feedback on building a recommendation system to solve a real-world problem of their choice and building the pitch deck to be presented during the final session. The deck should include a R/python script that reflect the main working principle of the recommendation system.        

### Readings  
There is no mandatory reading for these class but the following books, papers, and newspapers make excellent companions:

- [OpenAI documentation](https://openai.com/blog?authors=openai)
- [The Second Machine Age: Work, Progress, and Prosperity in a Time of Brilliant Technologies](https://www.amazon.com/Second-Machine-Age-Prosperity-Technologies/dp/0393350649) by Erik Brynjolfsson & Andrew McAfee    
- [Prediction Machines: The Simple Economics of Artificial Intelligence](https://www.amazon.com/Prediction-Machines-Economics-Artificial-Intelligence/dp/1633695670) by Ajay Agrawal, Joshua Gans & Avi Goldfarb        
- [AI Superpowers: China, Silicon Valley, And The New World Order](https://www.amazon.com/AI-Superpowers-China-Silicon-Valley/dp/132854639X) by Kai-Fu Lee    
- LeCun, Yann, Yoshua Bengio, and Geoffrey Hinton (2015) [Deep learning](https://www.nature.com/articles/nature14539), *Nature* (you don't have to understand it all - just skim through it)  
- Pierre-Alexandre Balland, Cristian Jara-Figueroa, Sergio G. Petralia, Mathieu P. A. Steijn, David L. Rigby & César A. Hidalgo (2020) [Complex economic activities concentrate in large cities](https://www.nature.com/articles/s41562-019-0803-3#:~:text=Complex%20economic%20activities%2C%20such%20as,as%20apparel%20or%20paper%20manufacturing.), *Nature Human Behavior*     
- Amazon's description of their [collaborative filtering AI system](https://www.amazon.science/the-history-of-amazons-recommendation-algorithm)    
- [Why data is the most valuable resource](https://www.economist.com/leaders/2017/05/06/the-worlds-most-valuable-resource-is-no-longer-oil-but-data) according to *The Economist*     

